insert into public.professors (id, "name", institution_id, slug, major_id) values
(1, 'Hendra Gunawan', 1, 'hendra-gunawan-ronqurge', 1),
(2, 'Johan Matheus Tuwankotta', 1, 'johan-matheus-tuwankotta-cyutatkk', 1),
(3, 'Marcus Wono Setya Budhi', 1, 'marcus-wono-setya-budhi-cehycvyt', 1),
(4, 'Pudji Astuti Waluyo', 1, 'pudji-astuti-waluyo-ndsmznuc', 1),
(5, 'Ahmad Muchlis', 1, 'ahmad-muchlis-thmuqmil', 1),
(6, 'Rinovia Mery Garnierita S.', 1, 'rinovia-mery-garnierita-s-hthliqsn', 1),
(7, 'Saladin Uttunggadewa', 1, 'saladin-uttunggadewa-ziyubhoq', 1),
(8, 'Elvira Kusniyanti', 1, 'elvira-kusniyanti-djwufohl', 1),
(9, 'Warsoma Djohan', 1, 'warsoma-djohan-xsobycut', 1),
(10, 'Gantina Rachmaputri', 1, 'gantina-rachmaputri-akxwiame', 1),
(11, 'M. Salman A.N.', 1, 'm-salman-an-gvmrevam', 1),
(12, 'Novriana Sumarti', 1, 'novriana-sumarti-opeavrgz', 1),
(13, 'Ade Candra Bayu', 1, 'ade-candra-bayu-wzgflmve', 1),
(14, 'Nuning Nuraini', 1, 'nuning-nuraini-jnvnzhmh', 1),
(15, 'Fajar Yuliawan', 1, 'fajar-yuliawan-pfuxolij', 1),
(16, 'Mochamad Apri', 1, 'mochamad-apri-btzrqubr', 1),
(17, 'Finny Oktariani', 1, 'finny-oktariani-arrlbaig', 1),
(18, 'Denny Ivanal Hakim', 1, 'denny-ivanal-hakim-fksunrjq', 1),
(19, 'Defita', 1, 'defita-srarjhsg', 1),
(20, 'Hilda Assiyatun', 1, 'hilda-assiyatun-igdqvtbj', 1),
(21, 'Iwan Pranoto', 1, 'iwan-pranoto-oljqgrmg', 1),
(22, 'Jalina Widjaja', 1, 'jalina-widjaja-tyakvxfi', 1),
(23, 'Aleams Barra', 1, 'aleams-barra-horgfjqx', 1),
(24, 'Djoko Suprijanto', 1, 'djoko-suprijanto-kkmllfta', 1),
(25, 'Ifronika', 1, 'ifronika-gcppupur', 1),
(26, 'L. Hari Wiryanto', 1, 'l-hari-wiryanto-fvqjpucq', 1),
(27, 'Aditya Purwa Santika', 1, 'aditya-purwa-santika-zyguugkc', 1),
(28, 'Agus Yodi Gunawan', 1, 'agus-yodi-gunawan-htndmiai', 1),
(29, 'Dewi Handayani', 1, 'dewi-handayani-lgijemne', 1),
(30, 'Irawati', 1, 'irawati-pmkbshdd', 1),
(31, 'Pritta Etriana Putri', 1, 'pritta-etriana-putri-qcqhlmvp', 1),
(32, 'Yudi Soeharyadi', 1, 'yudi-soeharyadi-lmyuyekz', 1),
(33, 'Sri Redjeki Pudjaprasetya F.', 1, 'sri-redjeki-pudjaprasetya-f-zosuwqpc', 1),
(34, 'Suhadi Wido Saputro', 1, 'suhadi-wido-saputro-yfwoxgbu', 1),
(35, 'Muhammad Islahuddin', 1, 'muhammad-islahuddin-mhjeioyp', 1),
(36, 'Afif Humam', 1, 'afif-humam-uimwsuvj', 1),
(37, 'Rizal Afgani', 1, 'rizal-afgani-xqcyrkbj', 1),
(38, 'Roberd Saragih', 1, 'roberd-saragih-kcepbycc', 1),
(39, 'Dellavitha', 1, 'dellavitha-rvsvkyfq', 1),
(40, 'Novry Erwina', 1, 'novry-erwina-gekftvvy', 1),
(41, 'Nana Nawawi Gaos', 1, 'nana-nawawi-gaos-nwgdqdhy', 1),
(42, 'Rudy Kusdiantara', 1, 'rudy-kusdiantara-ezolrqlj', 1),
(43, 'Janson Naiborhu', 1, 'janson-naiborhu-wkbikvam', 1),
(44, 'Oki Neswan', 1, 'oki-neswan-edfcuqvm', 1),
(45, 'Eric', 1, 'eric-djbrlfje', 1),
(46, 'Hanni Garminia Y.', 1, 'hanni-garminia-y-exvbabyt', 1),
(47, 'Muchtadi Intan Detiena', 1, 'muchtadi-intan-detiena-zhqqngug', 1),
(48, 'Erma Suwastika', 1, 'erma-suwastika-qwftdldm', 1),
(49, 'Ikha Magdalena', 1, 'ikha-magdalena-lrhoosar', 1),
(50, 'Dila Puspita', 1, 'dila-puspita-wryjxtyw', 1),
(51, 'Yuli Sri Afrianti', 1, 'yuli-sri-afrianti-sppozcee', 1),
(52, 'Sandy Vantika', 1, 'sandy-vantika-jkotgbgs', 1),
(53, 'Utriweni Mukhaiyar', 1, 'utriweni-mukhaiyar-uodbpfzo', 1),
(54, 'RR. Kurnia Novita Sari', 1, 'rr-kurnia-novita-sari-bxuxgpwm', 1),
(55, 'Kuntjoro Adji Sidarto', 1, 'kuntjoro-adji-sidarto-tdiftwjt', 1),
(56, 'Janny Lindiarni', 1, 'janny-lindiarni-ogxbhdkm', 1),
(57, 'Dumaria Rulina Tampubolon', 1, 'dumaria-rulina-tampubolon-ntpxxjms', 1),
(58, 'Edy Tri Baskoro', 1, 'edy-tri-baskoro-hqbctrny', 1),
(59, 'Sapto Wahyu Indratno', 1, 'sapto-wahyu-indratno-uaygtlim', 1),
(60, 'Udjianna Sekteria Pasaribu', 1, 'udjianna-sekteria-pasaribu-nmmklnus', 1),
(61, 'Khreshna Imaduddin Ahmad Syuhada', 1, 'khreshna-imaduddin-ahmad-syuhada-apzfbrcf', 1),
(62, 'Wahyu Srigutomo', 1, 'wahyu-srigutomo-hndvfzwg', 2),
(63, 'Pepen Arifin', 1, 'pepen-arifin-jlhfowco', 2),
(64, 'Fiki Taufik Akbar Sobar', 1, 'fiki-taufik-akbar-sobar-aarpwetd', 2),
(65, 'Sparisoma Viridi', 1, 'sparisoma-viridi-fnwsotsy', 2),
(66, 'Ferry Iskandar', 1, 'ferry-iskandar-fgibbiuk', 2),
(67, 'Triyanta', 1, 'triyanta-ecvnzgkj', 2),
(68, 'Enjang Jaenal Mustopa', 1, 'enjang-jaenal-mustopa-ydsidxoa', 2),
(69, 'Umar Fauzi', 1, 'umar-fauzi-nwqiubqz', 2),
(70, 'Bobby Eka Gunara', 1, 'bobby-eka-gunara-jkcvjlsu', 2),
(71, 'Triati Dewi Kencana Wungu', 1, 'triati-dewi-kencana-wungu-tandgjjj', 2),
(72, 'Daniel Kurnia', 1, 'daniel-kurnia-psyjbaff', 2),
(73, 'Nur Asiah Aprianti', 1, 'nur-asiah-aprianti-viixpsfj', 2),
(74, 'Rena Widita', 1, 'rena-widita-tzruwafv', 2),
(75, 'R. Bagus Endar Bachtiar N.', 1, 'r-bagus-endar-bachtiar-n-csdkyzvm', 2),
(76, 'Alexander Agustinus P. Iskandar', 1, 'alexander-agustinus-p-iskandar-vjlchedc', 2),
(77, 'Andy Octavian Latief', 1, 'andy-octavian-latief-cxsylqjy', 2),
(78, 'Herman', 1, 'herman-bdiidopn', 2),
(79, 'Agoes Soehianie', 1, 'agoes-soehianie-bnjtwajv', 2),
(80, 'Priastuti Wulandari', 1, 'priastuti-wulandari-vpwaqsas', 2),
(81, 'Fahdzi Muttaqien', 1, 'fahdzi-muttaqien-emzgnnta', 2),
(82, 'Berlinson Dominikus Napitu', 1, 'berlinson-dominikus-napitu-jgpoufqh', 2),
(83, 'Wahyu Hidayat', 1, 'wahyu-hidayat-vgzziebm', 2),
(84, 'Abdul Waris', 1, 'abdul-waris-gaclpsrq', 2),
(85, 'Rizal Kurniadi', 1, 'rizal-kurniadi-lqsbtfrl', 2),
(86, 'Neny Kurniasih', 1, 'neny-kurniasih-fxsqgytx', 2),
(87, 'Abdul Muizz Tri Pradipto', 1, 'abdul-muizz-tri-pradipto-vxtavrjg', 2),
(88, 'Widayani', 1, 'widayani-rvnqgvee', 2),
(89, 'Muhammad Miftahul Munir', 1, 'muhammad-miftahul-munir-tuximvhu', 2),
(90, 'Maria Evita', 1, 'maria-evita-oyxpfmjv', 2),
(91, 'Neni Surtiyeni', 1, 'neni-surtiyeni-nqkaqqmq', 2),
(92, 'Euis Sustini', 1, 'euis-sustini-lqfmezgu', 2),
(93, 'Agustinus Agung Nugroho Sulistyo Hutomo', 1, 'agustinus-agung-nugroho-sulistyo-hutomo-uakhnhwa', 2),
(94, 'Yudi Darma', 1, 'yudi-darma-fsgseknn', 2),
(95, 'Jusak Sali Kosasih', 1, 'jusak-sali-kosasih-wwyrckkx', 2),
(96, 'Toto Winata', 1, 'toto-winata-iyxrecsz', 2),
(97, 'Nurhasan', 1, 'nurhasan-lapoveof', 2),
(98, 'Harry Mahardika', 1, 'harry-mahardika-ncuysxdh', 2),
(99, 'Muhammad Rizqie Arbie', 1, 'muhammad-rizqie-arbie-zmgmwvtc', 2),
(100, 'Getbogi Hikmawan', 1, 'getbogi-hikmawan-mbpthfge', 2),
(101, 'Fatimah Arofiati Noor', 1, 'fatimah-arofiati-noor-lybfebfp', 2),
(102, 'Dhewa Edikresnha', 1, 'dhewa-edikresnha-cnqodzuj', 2),
(103, 'Dian Ahmad Hapidin', 1, 'dian-ahmad-hapidin-azhsgqta', 2),
(104, 'Agus Suroso', 1, 'agus-suroso-oyinimab', 2),
(105, 'Novitrian', 1, 'novitrian-ywraajsw', 2),
(106, 'Asril Pramutadi Andi Mustari', 1, 'asril-pramutadi-andi-mustari-mesmvbcu', 2),
(107, 'Rachmat Hidayat', 1, 'rachmat-hidayat-govnrign', 2),
(108, 'Irfan Dwi Aditya', 1, 'irfan-dwi-aditya-bosdygga', 2),
(109, 'Sidik Permana', 1, 'sidik-permana-rhdaoqnq', 2),
(110, 'Inge Magdalena Sutjahja', 1, 'inge-magdalena-sutjahja-alyubedz', 2),
(111, 'Pipit Fitriani', 1, 'pipit-fitriani-hjxaybig', 2),
(112, 'Akfiny Hasdi Aimon', 1, 'akfiny-hasdi-aimon-dljxdzwt', 2),
(113, 'Linus Ampang Pasasa', 1, 'linus-ampang-pasasa-qeogyqbl', 2),
(114, 'Maman Budiman', 1, 'maman-budiman-mqktlruz', 2),
(115, 'Gunawan Handayani', 1, 'gunawan-handayani-hbkdrubk', 2),
(116, 'Syeilendra Pramuditya', 1, 'syeilendra-pramuditya-fbpwnpqz', 2),
(117, 'Khairul Basar', 1, 'khairul-basar-dlhyplsr', 2),
(118, 'Nina Siti Aminah', 1, 'nina-siti-aminah-uvdmbipu', 2),
(119, 'Freddy Haryanto', 1, 'freddy-haryanto-slvnljgh', 2),
(120, 'Dwi Irwanto', 1, 'dwi-irwanto-hujjthlf', 2),
(121, 'Alamta Singarimbun', 1, 'alamta-singarimbun-laegieur', 2),
(122, 'Zaki Su`ud', 1, 'zaki-su`ud-aebrifmk', 2),
(123, 'Mikrajuddin', 1, 'mikrajuddin-ydgyfvkf', 2),
(124, 'Mitra Djamal', 1, 'mitra-djamal-ftjvbvyt', 2),
(125, 'Acep Purqon', 1, 'acep-purqon-bkkijolx', 2),
(126, 'Doddy Sutarno', 1, 'doddy-sutarno-tdygjuww', 2),
(127, 'Fourier Dzar Eljabbar', 1, 'fourier-dzar-eljabbar-shgbnyoi', 2),
(128, 'Freddy Permana Zen', 1, 'freddy-permana-zen-iyzjeeqx', 2),
(129, 'Idam Arif', 1, 'idam-arif-mvmjpwuw', 2),
(130, 'Suprijadi', 1, 'suprijadi-qsymdlhg', 2),
(131, 'Siti Nurul Khotimah', 1, 'siti-nurul-khotimah-pwsrxgcv', 2),
(132, 'Khairurrijal', 1, 'khairurrijal-vomuikzj', 2),
(133, 'Aprilia', 1, 'aprilia-rnrbwjni', 3),
(134, 'Kiki Vierdayanti', 1, 'kiki-vierdayanti-tgpavmel', 3),
(135, 'Mochamad Ikbal Arifyanto', 1, 'mochamad-ikbal-arifyanto-aqmfuony', 3),
(136, 'Ferry Mukharradi', 1, 'ferry-mukharradi-hxoqzzpp', 3),
(137, 'Yayan Sugianto', 1, 'yayan-sugianto-dhxdoutk', 3),
(138, 'Anton Timur Jaelani', 1, 'anton-timur-jaelani-ussbqswy', 3),
(139, 'Muhamad Irfan Hakim', 1, 'muhamad-irfan-hakim-lbsjzfvn', 3),
(140, 'Lucky Puspitarini', 1, 'lucky-puspitarini-rejssjoa', 3),
(141, 'Dhani Herdiwijaya', 1, 'dhani-herdiwijaya-zdybpkff', 3),
(142, 'Chatief Kunjaya', 1, 'chatief-kunjaya-qjmebclj', 3),
(143, 'Evan Irawan Akbar', 1, 'evan-irawan-akbar-pibxtujf', 3),
(144, 'Hesti Retno Tri Wulandari', 1, 'hesti-retno-tri-wulandari-qptyuyrd', 3),
(145, 'Endang Soegiartini', 1, 'endang-soegiartini-ylhhgvdb', 3),
(146, 'Taufiq Hidajat', 1, 'taufiq-hidajat-oheplkjz', 3),
(147, 'Hakim Luthfi Malasan', 1, 'hakim-luthfi-malasan-kdmhaxos', 3),
(148, 'Mahasenaputra', 1, 'mahasenaputra-bssxlaay', 3),
(149, 'Premana Wardayanti Premadi', 1, 'premana-wardayanti-premadi-huzlcwou', 3),
(150, 'Fargiza Abdan Malikul Mulki', 1, 'fargiza-abdan-malikul-mulki-uibwwzyh', 3),
(151, 'Anita Alni', 1, 'anita-alni-mgcsengj', 4),
(152, 'Fida Madayanti Warganegara', 1, 'fida-madayanti-warganegara-rkjslxgg', 4),
(153, 'Lia Dewi Juliawaty', 1, 'lia-dewi-juliawaty-spytsmhc', 4),
(154, 'I Made Arcana', 1, 'i-made-arcana-downmyir', 4),
(155, 'Untung Triadhi', 1, 'untung-triadhi-rlfcqfsd', 4),
(156, 'Rino Rakhmata Mukti', 1, 'rino-rakhmata-mukti-tehowynn', 4),
(157, 'Cynthia Linaya', 1, 'cynthia-linaya-isiamobw', 4),
(158, 'Rindia Maharani Putri', 1, 'rindia-maharani-putri-kbxazwbs', 4),
(159, 'Grandprix Thomryes Marth Kadja', 1, 'grandprix-thomryes-marth-kadja-srbbhpzn', 4),
(160, 'Ria Sri Rahayu', 1, 'ria-sri-rahayu-umjqqwsx', 4),
(161, 'Indra Noviandri', 1, 'indra-noviandri-uacoxnig', 4),
(162, 'Deana Wahyuningrum', 1, 'deana-wahyuningrum-hjsapnhe', 4),
(163, 'Bambang Prijamboedi', 1, 'bambang-prijamboedi-fdjjsjbu', 4),
(164, 'Irma Mulyani', 1, 'irma-mulyani-vnddqior', 4),
(165, 'Djulia Onggo', 1, 'djulia-onggo-xvbbxlwb', 4),
(166, 'Achmad Rochliadi', 1, 'achmad-rochliadi-ycjftnyv', 4),
(167, 'Sari Dewi Kurniasih Indrawan', 1, 'sari-dewi-kurniasih-indrawan-zbxjanww', 4),
(168, 'Rachmawati', 1, 'rachmawati-yfhmszvb', 4),
(169, 'Elvira Hermawati', 1, 'elvira-hermawati-clklmgvl', 4),
(170, 'Muhammad Ali Zulfikar', 1, 'muhammad-ali-zulfikar-otzhyeeu', 4),
(171, 'Rizki Fitriani', 1, 'rizki-fitriani-cztxqwxp', 4),
(172, 'Handajaya Rusli', 1, 'handajaya-rusli-xmqimnyd', 4),
(173, 'Dessy Natalia', 1, 'dessy-natalia-fxwwdhko', 4),
(174, 'Aep Patah', 1, 'aep-patah-emmkmhnj', 4),
(175, 'Yanti Rachmayanti', 1, 'yanti-rachmayanti-emhsnbyz', 4),
(176, 'Reza Aditama', 1, 'reza-aditama-hhdhjfxb', 4),
(177, 'Didin Mujahidin', 1, 'didin-mujahidin-aqtqdtdr', 4),
(178, 'Henry Setiyanto', 1, 'henry-setiyanto-phgjbvtp', 4),
(179, 'Rusnadi', 1, 'rusnadi-rimmsjtu', 4),
(180, 'Muhammad Iqbal', 1, 'muhammad-iqbal-mlvpsimh', 4),
(181, 'Zeily Nurachman', 1, 'zeily-nurachman-zsaudlsl', 4),
(182, 'Rukman Hertadi', 1, 'rukman-hertadi-mwvvrpla', 4),
(183, 'Muhamad Abdulkadir Martoprawiro', 1, 'muhamad-abdulkadir-martoprawiro-imiuklex', 4),
(184, 'Mia Ledyastuti', 1, 'mia-ledyastuti-toroouas', 4),
(185, 'Enny Ratnaningsih', 1, 'enny-ratnaningsih-ititjxub', 4),
(186, 'Fifi Fitriyah Masduki', 1, 'fifi-fitriyah-masduki-fpfyglea', 4),
(187, 'Nizar Happyana', 1, 'nizar-happyana-fvdmzeez', 4),
(188, 'Samitha Dewi Djajanti', 1, 'samitha-dewi-djajanti-oiheeawk', 4),
(189, 'Fainan Failamani', 1, 'fainan-failamani-hfawpmwa', 4),
(190, 'Yessi Permana', 1, 'yessi-permana-oaxkvpuy', 4),
(191, 'Robby Roswanda', 1, 'robby-roswanda-wnkvjmgp', 4),
(192, 'Ihsanawati', 1, 'ihsanawati-itpphnxq', 4),
(193, 'Dikhi Firmansyah', 1, 'dikhi-firmansyah-umkxnspu', 4),
(194, 'Muhammad Yudhistira Azis', 1, 'muhammad-yudhistira-azis-qpmggpsb', 4),
(195, 'Made Puspasari Widhiastuty', 1, 'made-puspasari-widhiastuty-mhcbyykk', 4),
(196, 'Veinardi Suendo', 1, 'veinardi-suendo-vnxntuwj', 4),
(197, 'Muhammad Bachri Amran', 1, 'muhammad-bachri-amran-qsxyunaz', 4),
(198, 'Yana Maolana Syah', 1, 'yana-maolana-syah-ufwuvzok', 4),
(199, 'Ade Danova', 1, 'ade-danova-qoudieky', 4),
(200, 'Akhmaloka', 1, 'akhmaloka-cnmxtqjf', 4),
(201, 'Alfredo Kono', 1, 'alfredo-kono-ybjfgizx', 4),
(202, 'Slamet Sutomo', 1, 'slamet-sutomo-wnaqsjqi', 5),
(203, 'Tuntun Salamatun Zen', 1, 'tuntun-salamatun-zen-ychypccv', 5),
(204, 'Budi Dermawan', 1, 'budi-dermawan-immrbxij', 9),
(205, 'Atthar Luqman Ivansyah', 1, 'atthar-luqman-ivansyah-bivrkkkn', 10),
(206, 'Euis Holisotan Hakim', 1, 'euis-holisotan-hakim-vswqbchd', 10),
(207, 'Ocke Kurniandi', 1, 'ocke-kurniandi-auvcmbvj', 11),
(208, 'Pingkan Aditiawati', 1, 'pingkan-aditiawati-vjjsqnet', 22),
(209, 'Kamarisima', 1, 'kamarisima-nqqaadpv', 22),
(210, 'Dea Indriani Astuti', 1, 'dea-indriani-astuti-rhgxtpxt', 22),
(211, 'Anriansyah Renggaman', 1, 'anriansyah-renggaman-ckrniqxf', 22),
(212, 'Maya Fitriyanti', 1, 'maya-fitriyanti-mngioumu', 22),
(213, 'Fenryco Pratama', 1, 'fenryco-pratama-fjajzdbo', 22),
(214, 'Intan Taufik', 1, 'intan-taufik-plbvcikn', 22),
(215, 'Magdalena Lenny Situmorang', 1, 'magdalena-lenny-situmorang-wkevhmpy', 22),
(216, 'Isty Adhitya Purwasena', 1, 'isty-adhitya-purwasena-aqfkeuqz', 22),
(217, 'Adi Pancoro', 1, 'adi-pancoro-cdksautr', 22),
(218, 'Husna Nugrahapraja', 1, 'husna-nugrahapraja-nnmwzedg', 22),
(219, 'Azzania Fibriani', 1, 'azzania-fibriani-llvdiddh', 22),
(220, 'I Nyoman Pugeg Aryantha', 1, 'i-nyoman-pugeg-aryantha-pnzvbgxl', 22),
(221, 'Mustika Dewi', 1, 'mustika-dewi-kgoffhcr', 22),
(222, 'Noor Rahmawati', 1, 'noor-rahmawati-fcitlndn', 22),
(223, 'Rizkita Rachmi Esyanti', 1, 'rizkita-rachmi-esyanti-tyrwtofz', 22),
(224, 'V. Sri Harjati Suhardi', 1, 'v-sri-harjati-suhardi-pdhqsdtl', 22),
(225, 'Mamat Kandar', 1, 'mamat-kandar-ndzfubyj', 22),
(226, 'Ernawati Arifin Giri-Rachman', 1, 'ernawati-arifin-girirachman-swntjbxs', 22),
(227, 'Karlia Meitha', 1, 'karlia-meitha-dpiyamjo', 22),
(228, 'Neil Priharto', 1, 'neil-priharto-silxijnk', 22),
(229, 'Gede Suantika', 1, 'gede-suantika-knxkuelk', 22),
(230, 'Angga Dwiartama', 1, 'angga-dwiartama-umiruann', 22),
(231, 'Sasanti Tarini', 1, 'sasanti-tarini-cseiirse', 22),
(232, 'Catur Riani', 1, 'catur-riani-bdbjbisj', 22),
(233, 'Tjandra Anggraeni', 1, 'tjandra-anggraeni-jnhsvqry', 23),
(234, 'Ayda Trisnawaty Yusuf', 1, 'ayda-trisnawaty-yusuf-qhgzaquf', 23),
(235, 'Sartika Indah Amalia Sudiarto', 1, 'sartika-indah-amalia-sudiarto-psutewnr', 23),
(236, 'Trimurti Hesti Wardini', 1, 'trimurti-hesti-wardini-fzdmsphx', 23),
(237, 'Novi Tri Astutiningsih', 1, 'novi-tri-astutiningsih-dljnoepz', 23),
(238, 'Arni Rahmawati Fahmi Sholihah', 1, 'arni-rahmawati-fahmi-sholihah-bdldhcky', 23),
(239, 'Rina Ratnasih Purnamahati', 1, 'rina-ratnasih-purnamahati-ljmxndhu', 23),
(240, 'Yeyet Setiawati', 1, 'yeyet-setiawati-bylqbfrg', 23),
(241, 'Eri Mustari', 1, 'eri-mustari-tshlmonl', 23),
(242, 'Tati Karliati', 1, 'tati-karliati-kptwokvj', 23),
(243, 'Elham Sumarga', 1, 'elham-sumarga-ehhglcnb', 23),
(244, 'Agustania Tjahjadimulja', 1, 'agustania-tjahjadimulja-vkjzdxgs', 23),
(245, 'Asep Suheri', 1, 'asep-suheri-luejzzob', 23),
(246, 'Alfi Rumidatul', 1, 'alfi-rumidatul-zbfrteel', 23),
(247, 'Sutrisno', 1, 'sutrisno-acczgpyi', 23),
(248, 'Ihak Sumardi', 1, 'ihak-sumardi-ypbvalhp', 23),
(249, 'Atmawi Darwis', 1, 'atmawi-darwis-glenoeaq', 23),
(250, 'Heri Rahman', 1, 'heri-rahman-lkhcmmxg', 23),
(251, 'Pujo', 1, 'pujo-llsfyukt', 23),
(252, 'Anne Hadiyane', 1, 'anne-hadiyane-jlwbdgbf', 23),
(253, 'Endah Sulistyawati', 1, 'endah-sulistyawati-yxzgykvc', 23),
(254, 'Ichsan Suwandhi', 1, 'ichsan-suwandhi-dkjydawl', 23),
(255, 'Yayat Hidayat', 1, 'yayat-hidayat-bxfrkzgn', 23),
(256, 'Ahmad Ridwan', 1, 'ahmad-ridwan-tdpigale', 23),
(257, 'Anggraini Barlian', 1, 'anggraini-barlian-dnwqwpuo', 23),
(258, 'Lulu Lusianti Fitri', 1, 'lulu-lusianti-fitri-prxniiik', 23),
(259, 'Indra Wibowo', 1, 'indra-wibowo-mlozwlfe', 23),
(260, 'Popi Septiani', 1, 'popi-septiani-pkyelwxl', 23),
(261, 'Fenny Martha Dwivany', 1, 'fenny-martha-dwivany-cofwwmlw', 23),
(262, 'Iriawati', 1, 'iriawati-hdzeijur', 23),
(263, 'Wardono Niloperbowo', 1, 'wardono-niloperbowo-gtgxvuon', 23),
(264, 'Devi Nandita Choesin', 1, 'devi-nandita-choesin-zaajxdgk', 23),
(265, 'Tati Suryati Syamsudin', 1, 'tati-suryati-syamsudin-jpbkprty', 23),
(266, 'Dian Rosleine', 1, 'dian-rosleine-zfeqlzab', 23),
(267, 'Aditya Dimas Pramudya', 1, 'aditya-dimas-pramudya-aqdfngjq', 23),
(268, 'Sony Heru Sumarsono', 1, 'sony-heru-sumarsono-szsbttsj', 23),
(269, 'Erly Marwani', 1, 'erly-marwani-xiahukvg', 23),
(270, 'Marselina Irasonia Tan', 1, 'marselina-irasonia-tan-hsncxyby', 23),
(271, 'Sony Suhandono', 1, 'sony-suhandono-vfseoxja', 23),
(272, 'Yooce Yustiana', 1, 'yooce-yustiana-zdafshty', 23),
(273, 'Sofiatin', 1, 'sofiatin-ttyhddvy', 23),
(274, 'Ahmad Faizal', 1, 'ahmad-faizal-wftmjxsa', 23),
(275, 'Taufikurahman', 1, 'taufikurahman-vcvqxphc', 23),
(276, 'Agus Dana Permana', 1, 'agus-dana-permana-njdbgvwa', 23),
(277, 'Ujang Dinar Husyari', 1, 'ujang-dinar-husyari-hwiqeskr', 23),
(278, 'Aep Supriyadi', 1, 'aep-supriyadi-ajvrpysb', 23),
(279, 'Lili Melani', 1, 'lili-melani-mvkgosxy', 23),
(280, 'Eka Mulya Alamsyah', 1, 'eka-mulya-alamsyah-bglrdqru', 23),
(281, 'Susana Paulina Dewi', 1, 'susana-paulina-dewi-jwgrhxob', 23),
(282, 'Noviana Vanawati', 1, 'noviana-vanawati-ugmumsps', 23),
(283, 'Sopandi Sunarya', 1, 'sopandi-sunarya-svtsftbx', 23),
(284, 'Yoyo Suhaya', 1, 'yoyo-suhaya-srjxggkh', 23),
(285, 'Rudi', 1, 'rudi-klaqvlrg', 23),
(286, 'Rika Alfianny', 1, 'rika-alfianny-elxcpjtj', 23),
(287, 'Ramadhani Eka Putra', 1, 'ramadhani-eka-putra-idoapxaz', 23),
(288, 'Endang Hernawan', 1, 'endang-hernawan-qipkfylf', 23),
(289, 'Robert Manurung', 1, 'robert-manurung-lrgeiecy', 24),
(290, 'Mochamad Firmansyah', 1, 'mochamad-firmansyah-kfccywtv', 24),
(291, 'Muhammad Yusuf Abduh', 1, 'muhammad-yusuf-abduh-qdkuznny', 24),
(292, 'Khairul Hadi Burhan', 1, 'khairul-hadi-burhan-vbkcqyfq', 24),
(293, 'Khalilan Lambangsari', 1, 'khalilan-lambangsari-nxdixjsj', 24),
(294, 'Sri Nanan B. Widiyanto', 1, 'sri-nanan-b-widiyanto-hkjkrwcu', 24),
(295, 'Estiyanti Ekawati', 1, 'estiyanti-ekawati-igsjwcjz', 24),
(296, 'Noviana Budianti', 1, 'noviana-budianti-rdktlxfm', 24),
(297, 'Dadang Sumardi', 1, 'dadang-sumardi-qltgcjbu', 24),
(298, 'Melia Famiola', 1, 'melia-famiola-zylpyxux', 24),
(299, 'Rijanti Rahaju Maulani', 1, 'rijanti-rahaju-maulani-zobgfbwm', 25),
(300, 'Asep Hidayat', 1, 'asep-hidayat-xdgqsvtt', 25),
(301, 'Rizki Fauziah Ramadhaini', 1, 'rizki-fauziah-ramadhaini-vjdzflvv', 25),
(302, 'Mia Rosmiati', 1, 'mia-rosmiati-roatqedh', 25),
(303, 'Arno Adi Kuntoro', 1, 'arno-adi-kuntoro-noshksyo', 25),
(304, 'Mohammad Farid', 1, 'mohammad-farid-ujzdlrft', 25),
(305, 'Aos', 1, 'aos-shsntljs', 25),
(306, 'Ahim Ruswandi', 1, 'ahim-ruswandi-hngohgxq', 25),
(307, 'Mulyaningrum', 1, 'mulyaningrum-xuvceydk', 25),
(308, 'Indratmo', 1, 'indratmo-uqllvfuv', 25),
(309, 'Tien Lastini', 1, 'tien-lastini-nvatyyqx', 26),
(310, 'Wawan Gunawan', 1, 'wawan-gunawan-vrjivmok', 26),
(311, 'Deddy Kurniadi', 1, 'deddy-kurniadi-cjrtbfij', 27),
(312, 'Brian Yuliarto', 1, 'brian-yuliarto-igryfcdz', 29),
(313, 'Alhilal Furqan', 1, 'alhilal-furqan-cjmdcqfs', 30),
(314, 'Intan Ahmad Musmeinan', 1, 'intan-ahmad-musmeinan-amhdguiw', 30),
(315, 'Elfahmi', 1, 'elfahmi-egmdatvd', 32),
(316, 'Kusnandar Anggadiredja', 1, 'kusnandar-anggadiredja-eaomdwqs', 32),
(317, 'Cindra Tri Yuniar', 1, 'cindra-tri-yuniar-ogrhmvlz', 32),
(318, 'Muhamad Insanu', 1, 'muhamad-insanu-ykckgzfu', 32),
(319, 'Rachmat Mauludin', 1, 'rachmat-mauludin-lbnoeuzz', 32),
(320, 'Lia Amalia', 1, 'lia-amalia-hrodwvtp', 32),
(321, 'Rika Hartati', 1, 'rika-hartati-ftrqjnsz', 32),
(322, 'Pratiwi Wikaningtyas', 1, 'pratiwi-wikaningtyas-nkqywceb', 32),
(323, 'Marlia Singgih', 1, 'marlia-singgih-neaylzzc', 32),
(324, 'Hubbi Nashrullah Muhammad', 1, 'hubbi-nashrullah-muhammad-ueqoarrg', 32),
(325, 'Muhammad Azhari', 1, 'muhammad-azhari-zfulngua', 32),
(326, 'Neng Fisheri Kurniati', 1, 'neng-fisheri-kurniati-avxowjbr', 32),
(327, 'Aluicia Anita Artarini', 1, 'aluicia-anita-artarini-ydbldtlh', 32),
(328, 'Anindyajati', 1, 'anindyajati-crizdcmt', 32),
(329, 'Hegar Pramastya', 1, 'hegar-pramastya-gcxaadlf', 32),
(330, 'Rahmana Emran Kartasasmita', 1, 'rahmana-emran-kartasasmita-gssyqixo', 32),
(331, 'Sophi Damayanti', 1, 'sophi-damayanti-cngjkwfo', 32),
(332, 'Fransiska Kurniawan', 1, 'fransiska-kurniawan-kcvucjtu', 32),
(333, 'Benny Permana', 1, 'benny-permana-htglyxbj', 32),
(334, 'Ilma Nugrahani', 1, 'ilma-nugrahani-trrcguwp', 32),
(335, 'Tursino', 1, 'tursino-cjlwnben', 32),
(336, 'Tasia Amelia', 1, 'tasia-amelia-xmssnryo', 32),
(337, 'Elin Julianti', 1, 'elin-julianti-lfspbeqk', 32),
(338, 'Daryono Hadi Tjahjono', 1, 'daryono-hadi-tjahjono-oyruypmo', 32),
(339, 'Defri Rizaldy', 1, 'defri-rizaldy-kfdwldwq', 32),
(340, 'Sukrasno', 1, 'sukrasno-qjrupoyn', 32),
(341, 'Lucy Dewi Nurhajati Sasongko', 1, 'lucy-dewi-nurhajati-sasongko-rdbovymy', 32),
(342, 'Amirah Adlia', 1, 'amirah-adlia-nokssdxw', 32),
(343, 'Maria Immaculata Iwo', 1, 'maria-immaculata-iwo-eeaidjqu', 32),
(344, 'Irianti Bahana Maulida Reyaan', 1, 'irianti-bahana-maulida-reyaan-gqmzxydr', 32),
(345, 'Afrillia Nuryanti Garmana', 1, 'afrillia-nuryanti-garmana-wzeuidvl', 32),
(346, 'Bhekti Pratiwi', 1, 'bhekti-pratiwi-aqcpkkis', 32),
(347, 'Dhyan Kusuma Ayuningtyas', 1, 'dhyan-kusuma-ayuningtyas-lrjxeebx', 32),
(348, 'Sundani Nurono', 1, 'sundani-nurono-rrzdvpcz', 32),
(349, 'Diky Mudhakir', 1, 'diky-mudhakir-olkxpfst', 32),
(350, 'Yuda Prasetya Nugraha', 1, 'yuda-prasetya-nugraha-vndcgzwp', 32),
(351, 'Tri Suciati', 1, 'tri-suciati-fbbzlhlj', 32),
(352, 'Ratna Annisa Utami', 1, 'ratna-annisa-utami-bmemlxbu', 32),
(353, 'Satrialdi', 1, 'satrialdi-dayrguae', 32),
(354, 'Nova Suliska', 1, 'nova-suliska-izmyozjt', 32),
(355, 'Saleh Wikarsa', 1, 'saleh-wikarsa-mynqgbsv', 32),
(356, 'I Ketut Adnyana', 1, 'i-ketut-adnyana-mmxkmcym', 32),
(357, 'Heni Rachmawati', 1, 'heni-rachmawati-eaosgtyk', 32),
(358, 'Irda Fidrianny', 1, 'irda-fidrianny-gikdxdqt', 32),
(359, 'Yeyet Cahyati Soemirtapura', 1, 'yeyet-cahyati-soemirtapura-bnuutpao', 32),
(360, 'Anis Sussieyani', 1, 'anis-sussieyani-huhcfnui', 32),
(361, 'Tjokorde Istri Armina Padmasawitri', 1, 'tjokorde-istri-armina-padmasawitri-rgqmxsxm', 32),
(362, 'Zulfan Zazuli', 1, 'zulfan-zazuli-wgzdnnri', 32),
(363, 'Siti Farah Rahmawati', 1, 'siti-farah-rahmawati-xyliodvf', 32),
(364, 'Tommy Apriantono', 1, 'tommy-apriantono-adyuuoiy', 33),
(365, 'Rini Syafriani', 1, 'rini-syafriani-gfqewtuq', 33),
(366, 'Tutus Gusdinar Kartawinata', 1, 'tutus-gusdinar-kartawinata-lilxmsiu', 33),
(367, 'Tomi Hendrayana', 1, 'tomi-hendrayana-xyhyzbni', 33),
(368, 'Nia Sri Ramania', 1, 'nia-sri-ramania-jxsmhysj', 33),
(369, 'Muhamad Fahmi Hasan', 1, 'muhamad-fahmi-hasan-oivwkiup', 33),
(370, 'Agung Dwi Juniarsyah', 1, 'agung-dwi-juniarsyah-xvfldbki', 33),
(371, 'Kusnaedi', 1, 'kusnaedi-kdwpwjly', 33),
(372, 'Samsul Bahri', 1, 'samsul-bahri-fufvxngv', 33),
(373, 'Didi Sunadi', 1, 'didi-sunadi-tiysveeu', 33),
(374, 'Yosi Agustina Hidayat', 1, 'yosi-agustina-hidayat-moclpqdb', 34),
(375, 'Yulianto Suharto', 1, 'yulianto-suharto-futtgcio', 34),
(376, 'Budhi Prihartono', 1, 'budhi-prihartono-otycdgkn', 35),
(377, 'Ferryanto', 1, 'ferryanto-acnpmazu', 36),
(378, 'Dwi Larso', 1, 'dwi-larso-aavvqbgn', 36),
(379, 'Narendra Kurnia Putra', 1, 'narendra-kurnia-putra-nbtmcpbv', 36),
(380, 'Suprijanto', 1, 'suprijanto-btakibkx', 36),
(381, 'Leo Aldianto', 1, 'leo-aldianto-evexweot', 36),
(382, 'Titah Yudhistira', 1, 'titah-yudhistira-ykgqpovs', 37),
(383, 'Ganda Marihot Simangunsong', 1, 'ganda-marihot-simangunsong-rnghvmal', 39),
(384, 'Yudhidya Wicaksana', 1, 'yudhidya-wicaksana-pvhdpdlm', 39),
(385, 'Simon Heru Prassetyo', 1, 'simon-heru-prassetyo-gkftkcgj', 39),
(386, 'Agus Haris Widayat', 1, 'agus-haris-widayat-artnmmtc', 39),
(387, 'Andy Yahya Al Hakim', 1, 'andy-yahya-al-hakim-qfhlnzpq', 39),
(388, 'Sendy Dwiki', 1, 'sendy-dwiki-yssiwzgi', 39),
(389, 'Ginting Jalu Kusuma', 1, 'ginting-jalu-kusuma-bqxhayhg', 39),
(390, 'Tri Karian', 1, 'tri-karian-tdfoqecp', 39),
(391, 'Nuhindro Priagung Widodo', 1, 'nuhindro-priagung-widodo-zqldcqdg', 39),
(392, 'Lilik Eko Widodo', 1, 'lilik-eko-widodo-dzdiwdui', 39),
(393, 'Teti Indriati', 1, 'teti-indriati-jjzadhwy', 39),
(394, 'Arie Naftali Hawu Hede', 1, 'arie-naftali-hawu-hede-eanzspqq', 39),
(395, 'Irwan Iskandar', 1, 'irwan-iskandar-rurzcxai', 39),
(396, 'Budi Sulistianto', 1, 'budi-sulistianto-odflgpbv', 39),
(397, 'Komang Anggayana', 1, 'komang-anggayana-eureubfz', 39),
(398, 'Bonita Dilasari', 1, 'bonita-dilasari-ecmtudqf', 39),
(399, 'Rudy Sayoga Gautama Benggolo', 1, 'rudy-sayoga-gautama-benggolo-voacvjjk', 39),
(400, 'Mohamad Nur Heriawan', 1, 'mohamad-nur-heriawan-xgibtskl', 39),
(401, 'Nurulhuda Halim', 1, 'nurulhuda-halim-dlyeaehh', 39),
(402, 'Syafrizal', 1, 'syafrizal-kczdahsu', 39),
(403, 'Fadhila Achmadi Rosyid', 1, 'fadhila-achmadi-rosyid-tnkyibab', 39),
(404, 'Arjo Prawoto Wibowo', 1, 'arjo-prawoto-wibowo-hjazlgiv', 39),
(405, 'Firly Rachmaditya Baskoro', 1, 'firly-rachmaditya-baskoro-monkcsfz', 39),
(406, 'R. Budi Sulistijo', 1, 'r-budi-sulistijo-uujvtzlw', 39),
(407, 'Ridho Kresna Wattimena', 1, 'ridho-kresna-wattimena-mamvhemi', 39),
(408, 'Salmawati', 1, 'salmawati-enlrxayx', 39),
(409, 'Tomy Alvin Rivai', 1, 'tomy-alvin-rivai-zdwmzcdz', 39),
(410, 'Zuher Syihab', 1, 'zuher-syihab-srmnmsng', 40),
(411, 'Taufan Marhaendrajana', 1, 'taufan-marhaendrajana-npsmcdxe', 40),
(412, 'Billal Maydika Aslam', 1, 'billal-maydika-aslam-hejimlgd', 40),
(413, 'Silvya Dewi Rahmawati', 1, 'silvya-dewi-rahmawati-ijthllsi', 40),
(414, 'Bonar Tua Halomoan Marbun', 1, 'bonar-tua-halomoan-marbun-zbkvxcjb', 40),
(415, 'Amega Yasutra', 1, 'amega-yasutra-fwytvdhr', 40),
(416, 'Ardhi Hakim Lumban Gaol', 1, 'ardhi-hakim-lumban-gaol-dtjawook', 40),
(417, 'Wijoyo Niti Daton', 1, 'wijoyo-niti-daton-hzipscvl', 40),
(418, 'Asep Kurnia Permadi', 1, 'asep-kurnia-permadi-pkpuqylf', 40),
(419, 'Muhammad Arif Naufaliansyah', 1, 'muhammad-arif-naufaliansyah-flsycuhl', 40),
(420, 'Dedy Irawan', 1, 'dedy-irawan-gpupkfre', 40),
(421, 'Doddy Abdassah', 1, 'doddy-abdassah-hwylaubs', 40),
(422, 'Adityawarman', 1, 'adityawarman-rshphptq', 40),
(423, 'Purnomo Yusgiantoro', 1, 'purnomo-yusgiantoro-wqfhtmyw', 40),
(424, 'Pahala Dominicus Sinurat', 1, 'pahala-dominicus-sinurat-kexrtrph', 40),
(425, 'Steven Chandra', 1, 'steven-chandra-lsbvwzhd', 40),
(426, 'Hasian P. Septoratno Siregar', 1, 'hasian-p-septoratno-siregar-lqkqylif', 40),
(427, 'Leksono', 1, 'leksono-whjpwxzj', 40),
(428, 'Rani Kurnia', 1, 'rani-kurnia-fireoiwt', 40),
(429, 'Utjok W. R. Siagian', 1, 'utjok-w-r-siagian-vyrgnmlz', 40),
(430, 'Sutopo', 1, 'sutopo-dtmjzbvu', 40),
(431, 'Ivan Kurnia', 1, 'ivan-kurnia-zwkyqeuj', 40),
(432, 'Dimas Taha Maulana', 1, 'dimas-taha-maulana-tlogrsle', 40),
(433, 'Nenny Miryani Saptadji', 1, 'nenny-miryani-saptadji-cauqmune', 40),
(434, 'Pudji Permadi', 1, 'pudji-permadi-fkpczewb', 40),
(435, 'Tedy Setiawan', 1, 'tedy-setiawan-yowjfmzq', 41),
(436, 'Ignatius Sonny Winardhie', 1, 'ignatius-sonny-winardhie-ypnkajtb', 41),
(437, 'Satria Bijaksana', 1, 'satria-bijaksana-jeruxbre', 41),
(438, 'Silvia Jannatul Fajar', 1, 'silvia-jannatul-fajar-nfnxzdic', 41),
(439, 'Zulfakriza', 1, 'zulfakriza-szofuusc', 41),
(440, 'Shindy Rosalia', 1, 'shindy-rosalia-ccplitmw', 41),
(441, 'Afnimar', 1, 'afnimar-yzzoutwm', 41),
(442, 'Andri Hendriyana', 1, 'andri-hendriyana-ksapcasx', 41),
(443, 'Tedi Yudistira', 1, 'tedi-yudistira-vansmnlt', 41),
(444, 'Fatkhan', 1, 'fatkhan-slatqhxj', 41),
(445, 'Antonius Nanang Tyasbudi Puspito', 1, 'antonius-nanang-tyasbudi-puspito-zfzeydbo', 41),
(446, 'Awali Priyono', 1, 'awali-priyono-rubbjgps', 41),
(447, 'Sigit Sukmono', 1, 'sigit-sukmono-hixglgbj', 41),
(448, 'Andri Dian Nugraha', 1, 'andri-dian-nugraha-raqzwpva', 41),
(449, 'Djoko Santoso', 1, 'djoko-santoso-gctnwbqo', 41),
(450, 'Faridz Nizar Ahmady', 1, 'faridz-nizar-ahmady-ofacgbfq', 41),
(451, 'Wawan Gunawan A. Kadir', 1, 'wawan-gunawan-a-kadir-ermuvrqb', 41),
(452, 'Sri Widiyantoro', 1, 'sri-widiyantoro-gzexckdg', 41),
(453, 'Warsa', 1, 'warsa-hofbgaro', 41),
(454, 'Dadi Abdurrahman', 1, 'dadi-abdurrahman-gkmqzfem', 41),
(455, 'Darharta Dahrin', 1, 'darharta-dahrin-htuitvks', 41),
(456, 'Setianingsih', 1, 'setianingsih-sorhqhvb', 41),
(457, 'Indra Gunawan', 1, 'indra-gunawan-dwinncyl', 41),
(458, 'Susanti Alawiyah', 1, 'susanti-alawiyah-bgxamfwu', 41),
(459, 'Ekkal Dinanto', 1, 'ekkal-dinanto-fyduvjap', 41),
(460, 'R. Mohammad Rachmat', 1, 'r-mohammad-rachmat-yqtowodz', 41),
(461, 'Agus Laesanpura', 1, 'agus-laesanpura-trrbptbm', 41),
(462, 'Fernando Lawrens', 1, 'fernando-lawrens-ukybuuyv', 41),
(463, 'Eko Januari Wahyudi', 1, 'eko-januari-wahyudi-twclohiv', 41),
(464, 'Alfian', 1, 'alfian-gendmlhc', 41),
(465, 'T.A. Sanny', 1, 'ta-sanny-dhrumlsp', 41),
(466, 'David Prambudi Sahara', 1, 'david-prambudi-sahara-mszdfosm', 41),
(467, 'Wahyu Triyoso', 1, 'wahyu-triyoso-hayfalxu', 41),
(468, 'Endra Gunawan', 1, 'endra-gunawan-rjszxtlb', 41),
(469, 'Hendra Grandis', 1, 'hendra-grandis-ywggqfrh', 41),
(470, 'Wahyudi Widyatmoko Parnadi', 1, 'wahyudi-widyatmoko-parnadi-rxrpckse', 41),
(471, 'Widodo', 1, 'widodo-cemzyvrt', 41),
(472, 'Dona Sita Ambarsari', 1, 'dona-sita-ambarsari-bvjdethz', 41),
(473, 'Edy Sanwani', 1, 'edy-sanwani-rklhvmvr', 42),
(474, 'Zulfiadi', 1, 'zulfiadi-fpxjlqhk', 42),
(475, 'Tria Laksana Achmad', 1, 'tria-laksana-achmad-brgwtvtw', 42),
(476, 'Zela Tanlega', 1, 'zela-tanlega-mriksprn', 42),
(477, 'Akhmad Ardian Korda', 1, 'akhmad-ardian-korda-byukemfg', 42),
(478, 'Fadhli Muhammad', 1, 'fadhli-muhammad-mimlilzk', 42),
(479, 'Taufiq Hidayat', 1, 'taufiq-hidayat-exnxkwqy', 42),
(480, 'Imam Santoso', 1, 'imam-santoso-tnocrued', 42),
(481, 'Dadan Suhendar', 1, 'dadan-suhendar-byrblvgm', 42),
(482, 'Eddy Agus Basuki', 1, 'eddy-agus-basuki-ovscmmrm', 42),
(483, 'Ismi Handayani', 1, 'ismi-handayani-dqvqyhdd', 42),
(484, 'Siti Khodijah', 1, 'siti-khodijah-ivneuyrf', 42),
(485, 'Mohammad Zaki Mubarok', 1, 'mohammad-zaki-mubarok-rpfuhejx', 42),
(486, 'Yogi', 1, 'yogi-ynwwwhsw', 44),
(487, 'Dyah Tjahyandari Suryaningtyas', 1, 'dyah-tjahyandari-suryaningtyas-lmyqvjtk', 44),
(488, 'Suryantini', 1, 'suryantini-fsiyxamu', 48),
(489, 'Prihadi Soemintadiredja', 1, 'prihadi-soemintadiredja-qzrekzac', 48),
(490, 'Alfend Rudyawan', 1, 'alfend-rudyawan-aqaezqoc', 48),
(491, 'Willy Adriansyah', 1, 'willy-adriansyah-izptranv', 48),
(492, 'Prihadi Setyo Darmanto', 1, 'prihadi-setyo-darmanto-ojeilsge', 48),
(493, 'Jooned Hendrarsakti', 1, 'jooned-hendrarsakti-bgwraahe', 48),
(494, 'Asep Saepuloh', 1, 'asep-saepuloh-afwailol', 48),
(495, 'Johan Arif', 1, 'johan-arif-jejkajid', 52),
(496, 'Djoko Santoso Abi Suroso', 1, 'djoko-santoso-abi-suroso-qznqlxpy', 52),
(497, 'Arini Murwindarti', 1, 'arini-murwindarti-hgctmaty', 52),
(498, 'Agus Mochamad Ramdhan', 1, 'agus-mochamad-ramdhan-ujcxizvo', 52),
(499, 'Benyamin Sapiie', 1, 'benyamin-sapiie-ufzxhbuo', 52),
(500, 'Meli Hadiana', 1, 'meli-hadiana-pyivlpfr', 52),
(501, 'Wahyu Probo Ananto', 1, 'wahyu-probo-ananto-flsrxyyw', 52),
(502, 'Rubiyanto Kapid', 1, 'rubiyanto-kapid-vfgewgzy', 52),
(503, 'Reynaldy Fifariz', 1, 'reynaldy-fifariz-cfnxuvze', 52),
(504, 'Asep Heri Patria Kesumajana', 1, 'asep-heri-patria-kesumajana-ysxzajna', 52),
(505, 'Chalid Idham Abdullah', 1, 'chalid-idham-abdullah-zvxjzctq', 52),
(506, 'Astyka Pamumpuni', 1, 'astyka-pamumpuni-mzttfoyr', 52),
(507, 'Niniek Rina Herdianita', 1, 'niniek-rina-herdianita-opvtscil', 52),
(508, 'Very Susanto', 1, 'very-susanto-rtxvhqnh', 52),
(509, 'Idham Andri Kurniawan', 1, 'idham-andri-kurniawan-dpcdfsqr', 52),
(510, 'I Gusti Bagus Eddy Sucipta', 1, 'i-gusti-bagus-eddy-sucipta-ycanooir', 52),
(511, 'Mirzam Abdurrachman', 1, 'mirzam-abdurrachman-jheqcnzk', 52),
(512, 'Aswan', 1, 'aswan-tilavzzw', 52),
(513, 'Yan Rizal R.', 1, 'yan-rizal-r-hgowlkjb', 52),
(514, 'Mika Rizki Puspaningrum', 1, 'mika-rizki-puspaningrum-dbwlyaei', 52),
(515, 'Dasapta Erwin Irawan', 1, 'dasapta-erwin-irawan-sfbptsby', 52),
(516, 'Dwiharso Nugroho', 1, 'dwiharso-nugroho-fexjdnux', 52),
(517, 'Lambok Hutasoit', 1, 'lambok-hutasoit-bmzewelo', 52),
(518, 'Andri Slamet Subandrio', 1, 'andri-slamet-subandrio-xmgmiauj', 52),
(519, 'Khoiril Anwar Maryunani', 1, 'khoiril-anwar-maryunani-eogujfrv', 52),
(520, 'Nurcahyo Indro Basuki', 1, 'nurcahyo-indro-basuki-dbkikbmc', 52),
(521, 'Deny Juanda Puradimaja', 1, 'deny-juanda-puradimaja-kcpypmtv', 52),
(522, 'Imam Achmad Sadisun', 1, 'imam-achmad-sadisun-dvzqycdv', 52),
(523, 'Rendy Dwi Kartiko', 1, 'rendy-dwi-kartiko-xcfqqbew', 52),
(524, 'Arif Susanto', 1, 'arif-susanto-yzfhrmas', 52),
(525, 'Eddy Ariyono Subroto', 1, 'eddy-ariyono-subroto-iqspydma', 52),
(526, 'Rachmy Fitriani', 1, 'rachmy-fitriani-tyiyrkxf', 53),
(527, 'Zadrach Ledoufij Dupe', 1, 'zadrach-ledoufij-dupe-dchirmvr', 53),
(528, 'Muhammad Rais Abdillah', 1, 'muhammad-rais-abdillah-qqyrjrti', 53),
(529, 'Plato Martuani Siregar', 1, 'plato-martuani-siregar-xiuhumnz', 53),
(530, 'Tri Wahyu Hadi', 1, 'tri-wahyu-hadi-kutuhxez', 53),
(531, 'Joko Wiratmo', 1, 'joko-wiratmo-jpiffwwr', 53),
(532, 'Musa Ali Mustofa', 1, 'musa-ali-mustofa-aawfujos', 53),
(533, 'Muhammad Ridho Syahputra', 1, 'muhammad-ridho-syahputra-raymeaer', 53),
(534, 'Nurjanna Joko Trilaksono', 1, 'nurjanna-joko-trilaksono-ezjutjyr', 53),
(535, 'Faiz Rohman Fajary', 1, 'faiz-rohman-fajary-mdbnhuty', 53),
(536, 'Rusmawan Suwarman', 1, 'rusmawan-suwarman-honmybsa', 53),
(537, 'Edi Riawan', 1, 'edi-riawan-qbjkcdec', 53),
(538, 'Atika', 1, 'atika-rxzveihw', 53),
(539, 'Mutiara Rachmat Putri', 1, 'mutiara-rachmat-putri-cxnhofao', 54),
(540, 'Lamona Irmudyawati Bernawis', 1, 'lamona-irmudyawati-bernawis-uyzveshs', 54),
(541, 'Aditya Rakhmat Kartadikaria', 1, 'aditya-rakhmat-kartadikaria-bcvlcorw', 54),
(542, 'Totok Suprijo', 1, 'totok-suprijo-ndflmhrl', 54),
(543, 'Suliskania Nurfitri', 1, 'suliskania-nurfitri-oundkenz', 54),
(544, 'Susanna', 1, 'susanna-jjksrzbv', 54),
(545, 'Ivonne Milichristi Radjawane', 1, 'ivonne-milichristi-radjawane-zumyjuyt', 54),
(546, 'Rima Rachmayani', 1, 'rima-rachmayani-itzvjgee', 54),
(547, 'Ayi Tarya', 1, 'ayi-tarya-yaogrewr', 54),
(548, 'Hamzah Latief', 1, 'hamzah-latief-xshgtymx', 54),
(549, 'Faruq Khadami', 1, 'faruq-khadami-uyvupxwv', 54),
(550, 'Nining Sari Ningsih', 1, 'nining-sari-ningsih-zdfpfixz', 54),
(551, 'Karina Aprilia Sujatmiko', 1, 'karina-aprilia-sujatmiko-lkzyhaai', 54),
(552, 'Riantini Virtriana', 1, 'riantini-virtriana-twkbmwdn', 55),
(553, 'Albertus Deliar', 1, 'albertus-deliar-czpektyq', 55),
(554, 'Akhmad Riqqi', 1, 'akhmad-riqqi-rrobxerg', 55),
(555, 'Sudarman', 1, 'sudarman-bbznkrhf', 55),
(556, 'Rizqi Abdulharis', 1, 'rizqi-abdulharis-svgaicqn', 55),
(557, 'Sella Lestari Nurmaulia', 1, 'sella-lestari-nurmaulia-srdukuwp', 55),
(558, 'Irwan Meilano', 1, 'irwan-meilano-uqacgxix', 55),
(559, 'Ratri Widyastuti', 1, 'ratri-widyastuti-xkbkivvu', 55),
(560, 'Andri Hernandi', 1, 'andri-hernandi-wajepagh', 55),
(561, 'Dwi Wisayantono', 1, 'dwi-wisayantono-pilipymz', 55),
(562, 'Nabila Sofia Eryan Putri', 1, 'nabila-sofia-eryan-putri-tfzzxjec', 55),
(563, 'Kosasih Prijatna', 1, 'kosasih-prijatna-urgkaztk', 55),
(564, 'Wedyanto', 1, 'wedyanto-rlhzesuj', 55),
(565, 'Vera Sadarviana', 1, 'vera-sadarviana-xxdsmvqp', 55),
(566, 'Heri Andreas', 1, 'heri-andreas-qeqkbqdt', 55),
(567, 'Agustinus Bambang Setyadji', 1, 'agustinus-bambang-setyadji-pemhuvig', 55),
(568, 'Dina Anggreni Sarsito', 1, 'dina-anggreni-sarsito-mknqpzan', 55),
(569, 'Zamzam Akhmad Jamaluddin Tanuwijaya', 1, 'zamzam-akhmad-jamaluddin-tanuwijaya-wpsfdfuc', 55),
(570, 'Dudy Darmawan Wijaya', 1, 'dudy-darmawan-wijaya-cruvcfoo', 55),
(571, 'Gabriella Alodia', 1, 'gabriella-alodia-myjsnvlh', 55),
(572, 'Irwan Gumilar', 1, 'irwan-gumilar-msiahrjm', 55),
(573, 'Dhota Pradipta', 1, 'dhota-pradipta-xpractnq', 55),
(574, 'Asep Yusup Saptari', 1, 'asep-yusup-saptari-bmbuhkwy', 55),
(575, 'Alfita Puspa Handayani', 1, 'alfita-puspa-handayani-cbtbenro', 55),
(576, 'Poerbandono', 1, 'poerbandono-kmuqgqzu', 55),
(577, 'Wiwin Windupranata', 1, 'wiwin-windupranata-pucvhpgq', 55),
(578, 'Eka Djunarsjah', 1, 'eka-djunarsjah-iljruzqe', 55),
(579, 'Fickrie Muhammad', 1, 'fickrie-muhammad-umhezubp', 55),
(580, 'Deni Suwardhi', 1, 'deni-suwardhi-jczcgrbi', 55),
(581, 'Agung Budi Harto', 1, 'agung-budi-harto-avsrznyq', 55),
(582, 'Budhy Soeksmantono', 1, 'budhy-soeksmantono-ohwpqnfl', 55),
(583, 'Hasanuddin Zainal Abidin', 1, 'hasanuddin-zainal-abidin-nhkbcuyl', 55),
(584, 'Teguh Purnama Sidiq', 1, 'teguh-purnama-sidiq-ghggzoja', 55),
(585, 'Maria Sekar Proborukmi', 1, 'maria-sekar-proborukmi-tdbyfacy', 57),
(586, 'Jahdi Zaim', 1, 'jahdi-zaim-jbmsadun', 57),
(587, 'Anjar Dimara Sakti', 1, 'anjar-dimara-sakti-bzoyygtr', 60),
(588, 'Ketut Wikantika', 1, 'ketut-wikantika-fvvwpysg', 63),
(589, 'Hary Devianto', 1, 'hary-devianto-wigwyhmm', 64),
(590, 'Pri Januar Gusnawan', 1, 'pri-januar-gusnawan-wpthuotp', 64),
(591, 'Yazid Bindar', 1, 'yazid-bindar-wlamccku', 64),
(592, 'Megawati Zunita', 1, 'megawati-zunita-wzmwkhjv', 64),
(593, 'Melia Laniwati Gunawan', 1, 'melia-laniwati-gunawan-qytwjggm', 64),
(594, 'Tirto Prakoso', 1, 'tirto-prakoso-wwqivntl', 64),
(595, 'Herri Susanto', 1, 'herri-susanto-qmsjaein', 64),
(596, 'Akhmad Zainal Abidin', 1, 'akhmad-zainal-abidin-ykkgbylp', 64),
(597, 'Irwan Noezar', 1, 'irwan-noezar-vldcrfhl', 64),
(598, 'Sanggono Adisasmito', 1, 'sanggono-adisasmito-emyhgwfi', 64),
(599, 'Vita Wonoputri', 1, 'vita-wonoputri-qcaexqbd', 64),
(600, 'Khoiruddin', 1, 'khoiruddin-rabupvih', 64),
(601, 'Carolus Borromeus Rasrendra', 1, 'carolus-borromeus-rasrendra-sesudsao', 64),
(602, 'Haryo Pandu Winoto', 1, 'haryo-pandu-winoto-cbgzhmbx', 64),
(603, 'Meiti Pratiwi', 1, 'meiti-pratiwi-hivmgvax', 64),
(604, 'Jenny Rizkiana', 1, 'jenny-rizkiana-enalenal', 64),
(605, 'Lienda Aliwarga', 1, 'lienda-aliwarga-knkqidau', 64),
(606, 'Dian Shofinita', 1, 'dian-shofinita-eynkvjqz', 64),
(607, 'Elvi Restiawaty', 1, 'elvi-restiawaty-gbidnlmw', 64),
(608, 'Yogi Wibisono Budhi', 1, 'yogi-wibisono-budhi-ufprbvpb', 64),
(609, 'Anggit Raksajati', 1, 'anggit-raksajati-mfhrpjnt', 64),
(610, 'Wibawa Hendra Saputera', 1, 'wibawa-hendra-saputera-wgjsbqlm', 64),
(611, 'Dwiwahju Sasongko', 1, 'dwiwahju-sasongko-kpwysqpz', 64),
(612, 'Fadhli', 1, 'fadhli-bgosufqi', 64),
(613, 'Made Tri Ari Penia Kresnowati', 1, 'made-tri-ari-penia-kresnowati-ktvqeuoe', 64),
(614, 'Anita Kusuma Wardani', 1, 'anita-kusuma-wardani-kqrxmcjm', 64),
(615, 'Tjokorde Walmiki Samadhi', 1, 'tjokorde-walmiki-samadhi-opezniey', 64),
(616, 'Winny Wulandari', 1, 'winny-wulandari-iddphucr', 64),
(617, 'Hafis Pratama Rendra Graha', 1, 'hafis-pratama-rendra-graha-aspstrng', 64),
(618, 'Ronny Purwadi', 1, 'ronny-purwadi-oevwbtbn', 64),
(619, 'I.G.B. Ngurah Makertihartha', 1, 'igb-ngurah-makertihartha-griodkjn', 64),
(620, 'Dendy Adityawarman', 1, 'dendy-adityawarman-ldelszhk', 64),
(621, 'Ardiyan Harimawan', 1, 'ardiyan-harimawan-myswhwyx', 64),
(622, 'Retno Gumilang Dewi', 1, 'retno-gumilang-dewi-vygxfgxu', 64),
(623, 'I Gede Wenten', 1, 'i-gede-wenten-ubfkoeuw', 64),
(624, 'Kiki Adi Kurnia', 1, 'kiki-adi-kurnia-mrrieumx', 64),
(625, 'Graecia Lugito', 1, 'graecia-lugito-hlqtvono', 64),
(626, 'Danu Ariono', 1, 'danu-ariono-pvmdvnuu', 64),
(627, 'Tjandra Setiadi', 1, 'tjandra-setiadi-igbcchhh', 64),
(628, 'Helen Julian', 1, 'helen-julian-pnnbifkx', 64),
(629, 'Aqsha', 1, 'aqsha-jslwclzf', 64),
(630, 'Pramujo Widiatmoko', 1, 'pramujo-widiatmoko-dqdgjjzb', 64),
(631, 'Ukan Sukandar', 1, 'ukan-sukandar-vcbyuzal', 64),
(632, 'Johnner Sitompul', 1, 'johnner-sitompul-hrivkppl', 64),
(633, 'I Dewa Gede Arsa Putrawan', 1, 'i-dewa-gede-arsa-putrawan-vjgwcqye', 64),
(634, 'Tri Partono Adhi', 1, 'tri-partono-adhi-axqhhvgy', 64),
(635, 'Antonius Indarto', 1, 'antonius-indarto-foxuxwti', 64),
(636, 'Astri Nur Istyami', 1, 'astri-nur-istyami-ymitfxlc', 64),
(637, 'Miranti Indar Mandasari', 1, 'miranti-indar-mandasari-pdoxidbf', 65),
(638, 'Ganes Shukri', 1, 'ganes-shukri-exsqklyy', 65),
(639, 'Ashari budi Nugraha', 1, 'ashari-budi-nugraha-yhylridl', 65),
(640, 'Hermawan Kresno Dipojono', 1, 'hermawan-kresno-dipojono-jiqiwnwj', 65),
(641, 'Vebi Nadhira', 1, 'vebi-nadhira-mklrwmlg', 65),
(642, 'Anugrah Sabdono Sudarsono', 1, 'anugrah-sabdono-sudarsono-okvngwgy', 65),
(643, 'Rizki Armanto Mangkuto', 1, 'rizki-armanto-mangkuto-jxhgjbwv', 65),
(644, 'Ni Putu Amanda Nitidara', 1, 'ni-putu-amanda-nitidara-cuzcjmli', 65),
(645, 'Ahmad Nuruddin', 1, 'ahmad-nuruddin-hizbooep', 65),
(646, 'Mohammad Kemal Agusta', 1, 'mohammad-kemal-agusta-rvdnsnvm', 65),
(647, 'Irsyad Nashirul Haq', 1, 'irsyad-nashirul-haq-orjsdeor', 65),
(648, 'Fadjar Fathurrahman', 1, 'fadjar-fathurrahman-guoelsyn', 65),
(649, 'Muhammad Haris Mahyuddin', 1, 'muhammad-haris-mahyuddin-oephwelg', 65),
(650, 'Rahmat Romadhon', 1, 'rahmat-romadhon-oburlzoz', 65),
(651, 'Nugraha', 1, 'nugraha-ovkyaass', 65),
(652, 'R. Sugeng Joko Sarwono', 1, 'r-sugeng-joko-sarwono-bhbgthqo', 65),
(653, 'Endang Juliastuti', 1, 'endang-juliastuti-thowaxoc', 65),
(654, 'Ayu Gareta Risangtuni', 1, 'ayu-gareta-risangtuni-ezpphtnu', 65),
(655, 'Eko Mursito Budi', 1, 'eko-mursito-budi-bcmzzxzf', 65),
(656, 'R. Triyogo', 1, 'r-triyogo-jwocogdf', 65),
(657, 'Justin Pradipta', 1, 'justin-pradipta-pkucejgq', 65),
(658, 'Damar Rastri Adhika', 1, 'damar-rastri-adhika-osqwwpek', 65),
(659, 'Agung Budiyono', 1, 'agung-budiyono-pyejduxj', 65),
(660, 'Iwan Prasetiyo', 1, 'iwan-prasetiyo-qthpcqgc', 65),
(661, 'Adhitya Gandaryus Saputro', 1, 'adhitya-gandaryus-saputro-wqcgkklt', 65),
(662, 'Augie Widyotriatmo', 1, 'augie-widyotriatmo-lnymlhfa', 65),
(663, 'Faqihza Mukhlish', 1, 'faqihza-mukhlish-tfhemwrb', 65),
(664, 'Parsaulian Ishaya Siregar', 1, 'parsaulian-ishaya-siregar-grxrbscq', 65),
(665, 'Yul Yunazwin', 1, 'yul-yunazwin-maugpvvg', 65),
(666, 'Edi Leksono', 1, 'edi-leksono-zcftgwmg', 65),
(667, 'Endra Joelianto', 1, 'endra-joelianto-eescppzj', 65),
(668, 'Made Andriani', 1, 'made-andriani-zwzsiktx', 66),
(669, 'Abdul Hakim Halim', 1, 'abdul-hakim-halim-pebciwiw', 66),
(670, 'Ari Widyanti', 1, 'ari-widyanti-zyokhzyc', 66),
(671, 'Andi Cakravastia Arisaputra Raja', 1, 'andi-cakravastia-arisaputra-raja-tykrtfwg', 66),
(672, 'Kadarsah Suryadi', 1, 'kadarsah-suryadi-kmqlmfug', 66),
(673, 'Joko Siswanto', 1, 'joko-siswanto-wrflurbq', 66),
(674, 'Tota Simatupang', 1, 'tota-simatupang-yabvfyjy', 66),
(675, 'Darwin', 1, 'darwin-wqeptqry', 66),
(676, 'Anggita Leviastuti', 1, 'anggita-leviastuti-evfkicpy', 66),
(677, 'Rully Tri Cahyono', 1, 'rully-tri-cahyono-yizzphfz', 66),
(678, 'Dradjad Irianto', 1, 'dradjad-irianto-xekpmchb', 66),
(679, 'Muhammad Akbar', 1, 'muhammad-akbar-zrrbqzgx', 66),
(680, 'Suprayogi', 1, 'suprayogi-ojguxpla', 66),
(681, 'Saskia Puspa Kenaka', 1, 'saskia-puspa-kenaka-bigkqdth', 66),
(682, 'Aldila Rizkiana', 1, 'aldila-rizkiana-aufrkmvs', 66),
(683, 'Rajesri', 1, 'rajesri-xxwjepoq', 66),
(684, 'Dissa Riandaso Chandra', 1, 'dissa-riandaso-chandra-ysoejnpu', 66),
(685, 'Ni Luh Saddhwi Saraswati Adnyani', 1, 'ni-luh-saddhwi-saraswati-adnyani-jalmgfbx', 66),
(686, 'Anas Maruf', 1, 'anas-maruf-muakvpmo', 66),
(687, 'Sukoyo', 1, 'sukoyo-amryxpue', 66),
(688, 'Khoirul Muslim', 1, 'khoirul-muslim-zusrqead', 66),
(689, 'Dwita Astari Pujiartati', 1, 'dwita-astari-pujiartati-zxfzelpa', 66),
(690, 'Herman Rahadian Soetisna', 1, 'herman-rahadian-soetisna-tbijrtbt', 66),
(691, 'Hardianto Iridiastadi', 1, 'hardianto-iridiastadi-bpvqmdmk', 66),
(692, 'Veterina Nosadila Riaventin', 1, 'veterina-nosadila-riaventin-tnfigmqb', 66),
(693, 'Ghaida Fatcha Mubiena', 1, 'ghaida-fatcha-mubiena-lyapfxzs', 66),
(694, 'Hasrini Sari', 1, 'hasrini-sari-pbvojxfz', 66),
(695, 'Iwan Inrawan Wiratmadja', 1, 'iwan-inrawan-wiratmadja-ojaohxrc', 66),
(696, 'Wildan Trusaji', 1, 'wildan-trusaji-mvklvrmd', 66),
(697, 'Bermawi Priyatna Iskandar', 1, 'bermawi-priyatna-iskandar-coxxbxlx', 66),
(698, 'Lucia Diawati', 1, 'lucia-diawati-tjkypfvm', 66),
(699, 'Wisnu Aribowo', 1, 'wisnu-aribowo-ehzjpzhp', 66),
(700, 'Isa Setiasyah Toha', 1, 'isa-setiasyah-toha-aatwqknf', 66),
(701, 'Mohammad Miradj Isnaini', 1, 'mohammad-miradj-isnaini-gzxgpcoc', 66),
(702, 'Rachmawati Wangsaputra', 1, 'rachmawati-wangsaputra-hteaqamr', 66),
(703, 'Yassierli', 1, 'yassierli-hcefkgoc', 66),
(704, 'Fariz Muharram Hasby', 1, 'fariz-muharram-hasby-eppjikre', 66),
(705, 'Fathiro Hutama Reksa Putra', 1, 'fathiro-hutama-reksa-putra-qoppkhkh', 66),
(706, 'Dianika Lestari', 1, 'dianika-lestari-wpatpzau', 67),
(707, 'Giovanni Arneldi Sumampouw', 1, 'giovanni-arneldi-sumampouw-mwetqwoh', 67),
(708, 'Tatang Hernas', 1, 'tatang-hernas-swoisiqb', 67),
(709, 'Burhannudin', 1, 'burhannudin-mszkpdmz', 67),
(710, 'Yohanes Andre Situmorang', 1, 'yohanes-andre-situmorang-hsxdcyok', 69),
(711, 'Bambang Sunendar', 1, 'bambang-sunendar-bnbjxone', 72),
(712, 'Senator Nur Bahagia', 1, 'senator-nur-bahagia-bgbapacr', 73),
(713, 'Agung Wahyu', 1, 'agung-wahyu-goigtshd', 79),
(714, 'Eniman Yunus Syamsuddin', 1, 'eniman-yunus-syamsuddin-tjqhsxde', 79),
(715, 'Arwindra Rizqiawan', 1, 'arwindra-rizqiawan-kcacwdwt', 79),
(716, 'Arif Sasongko', 1, 'arif-sasongko-qjdinjwl', 79),
(717, 'Muhammad Ogin Hasanuddin', 1, 'muhammad-ogin-hasanuddin-uxzjdzge', 79),
(718, 'Muhammad Iqbal Arsyad', 1, 'muhammad-iqbal-arsyad-uaqvohur', 79),
(719, 'Yulyan Wahyu Hadi', 1, 'yulyan-wahyu-hadi-mooviekd', 79),
(720, 'Fetty Fitriyanti Lubis', 1, 'fetty-fitriyanti-lubis-kaarsuqo', 79),
(721, 'Albarda', 1, 'albarda-qfcoabsc', 79),
(722, 'Dimitri Mahayana', 1, 'dimitri-mahayana-ectebpjb', 79),
(723, 'Budiman Dabarsyah', 1, 'budiman-dabarsyah-bdjusavu', 79),
(724, 'Elvayandri', 1, 'elvayandri-drokokox', 79),
(725, 'Agung Harsoyo', 1, 'agung-harsoyo-fysqcvuy', 79),
(726, 'Armein Z.R. Langi', 1, 'armein-zr-langi-wmlvdfwi', 79),
(727, 'Muhammad Amin Sulthoni', 1, 'muhammad-amin-sulthoni-yxrxcncz', 79),
(728, 'Nana Sutisna', 1, 'nana-sutisna-klxjztpk', 79),
(729, 'Yusuf Kurniawan', 1, 'yusuf-kurniawan-glffoype', 79),
(730, 'Beni Rio Hermanto', 1, 'beni-rio-hermanto-nobaxvyc', 79),
(731, 'Mervin Tangguar Hutabarat', 1, 'mervin-tangguar-hutabarat-owjhbxeh', 79),
(732, 'Achmad Fuad Masud', 1, 'achmad-fuad-masud-wbordfux', 79),
(733, 'Yoanes Bandung', 1, 'yoanes-bandung-oalthpsp', 79),
(734, 'Egi Muhammad Idris Hidayat', 1, 'egi-muhammad-idris-hidayat-zdwdfjrn', 79),
(735, 'Kusprasapta Mutijarsa', 1, 'kusprasapta-mutijarsa-fitcmpao', 79),
(736, 'Reza Darmakusuma', 1, 'reza-darmakusuma-ofpwppiy', 79),
(737, 'Irman Idris', 1, 'irman-idris-mhchouqh', 79),
(738, 'Arief Syaichu Rohman', 1, 'arief-syaichu-rohman-rihdiroj', 79),
(739, 'Pranoto Hidaya Rusmin', 1, 'pranoto-hidaya-rusmin-vpfiaudg', 79),
(740, 'Lenni Yulianti', 1, 'lenni-yulianti-vvuslyeh', 79),
(741, 'Emir Mauludi Husni', 1, 'emir-mauludi-husni-jnykxpkp', 79),
(742, 'Adi Indrayanto', 1, 'adi-indrayanto-xfbkuimj', 79),
(743, 'Akhmadi Surawijaya', 1, 'akhmadi-surawijaya-qkwuwrdh', 79),
(744, 'Rahadian Yusuf', 1, 'rahadian-yusuf-tovsbmwj', 79),
(745, 'Ary Setijadi Prihatmanto', 1, 'ary-setijadi-prihatmanto-gjtbltgj', 79),
(746, 'Waskita Adijarto', 1, 'waskita-adijarto-mycodiob', 79),
(747, 'Tati Latifah Erawati Rajab', 1, 'tati-latifah-erawati-rajab-bvpazata', 79),
(748, 'Astri Handayani', 1, 'astri-handayani-eybvyzfy', 79),
(749, 'Hilwadi Hindersah', 1, 'hilwadi-hindersah-vhdzbdbx', 79),
(750, 'Allya Paramita Koesoema', 1, 'allya-paramita-koesoema-fuoxfvic', 79),
(751, 'Trio Adiono', 1, 'trio-adiono-hijxntre', 79),
(752, 'Tri Desmana Rachmildha', 1, 'tri-desmana-rachmildha-ikpsmxiv', 79),
(753, 'Pradita Octoviandiningrum Hadi', 1, 'pradita-octoviandiningrum-hadi-sfezquib', 79),
(754, 'Achmad Munir', 1, 'achmad-munir-vdwsgtog', 79),
(755, 'Suwarno', 1, 'suwarno-shvjoxgu', 79),
(756, 'Bambang Anggoro Soedjarno P.', 1, 'bambang-anggoro-soedjarno-p-vunfhfod', 79),
(757, 'Carmadi Machbub', 1, 'carmadi-machbub-kdwuzrsb', 79),
(758, 'Anggera Bayuwindra', 1, 'anggera-bayuwindra-oskqjtqa', 79),
(759, 'Nanang Hariyanto', 1, 'nanang-hariyanto-lmsufehv', 79),
(760, 'Fathin Saifur Rahman', 1, 'fathin-saifur-rahman-phqjrryb', 79),
(761, 'Kevin Marojahan Banjar Nahor', 1, 'kevin-marojahan-banjar-nahor-qbkosjcc', 79),
(762, 'Bambang Riyanto Trilaksono', 1, 'bambang-riyanto-trilaksono-hzugtszl', 79),
(763, 'Yani Widyani', 1, 'yani-widyani-gwbhtopv', 80),
(764, 'Wikan Danar Sunindyo', 1, 'wikan-danar-sunindyo-vapfpdnk', 80),
(765, 'Rizal Dwi Prayogo', 1, 'rizal-dwi-prayogo-uxundmql', 80),
(766, 'Riza Satria Perdana', 1, 'riza-satria-perdana-omfdoqbd', 80),
(767, 'Farrell Yodihartomo', 1, 'farrell-yodihartomo-idzgggks', 80),
(768, 'Habibur Muhaimin', 1, 'habibur-muhaimin-uhayhwav', 80),
(769, 'Nur Ulfa Maulidevi', 1, 'nur-ulfa-maulidevi-kwfyanqz', 80),
(770, 'Fariska Zakhralativa Ruskanda', 1, 'fariska-zakhralativa-ruskanda-fukrvvdp', 80),
(771, 'Rinaldi', 1, 'rinaldi-meyabhto', 80),
(772, 'Rila Mandala', 1, 'rila-mandala-lilltgti', 80),
(773, 'Judhi Santoso', 1, 'judhi-santoso-nerhjfid', 80),
(774, 'Ayu Purwarianti', 1, 'ayu-purwarianti-gzvvgxsw', 80),
(775, 'Achmad Imam Kistijantoro', 1, 'achmad-imam-kistijantoro-bwlbxfwu', 80),
(776, 'Infall Syafalni', 1, 'infall-syafalni-esdqgdms', 80),
(777, 'Dessi Puji Lestari', 1, 'dessi-puji-lestari-eunuuxba', 80),
(778, 'Tricya Esterina Widagdo', 1, 'tricya-esterina-widagdo-svrngqol', 80),
(779, 'Latifa Dwiyanti', 1, 'latifa-dwiyanti-yqvqllbe', 80),
(780, 'Yudistira Dwi Wardhana Asnar', 1, 'yudistira-dwi-wardhana-asnar-cxgvwozo', 80),
(781, 'Afwarman', 1, 'afwarman-jbihipll', 80),
(782, 'Wervyan Shalannanda', 1, 'wervyan-shalannanda-iiqfnvkl', 80),
(783, 'Ahmad Izzuddin', 1, 'ahmad-izzuddin-tljbtsav', 80),
(784, 'Joko Suryana', 1, 'joko-suryana-zydmuvwx', 80),
(785, 'Saiful Akbar', 1, 'saiful-akbar-jjgqhhnq', 80),
(786, 'Windy Gambetta', 1, 'windy-gambetta-gimptygd', 80),
(787, 'Dicky Prima Satya', 1, 'dicky-prima-satya-otsqwtvc', 80),
(788, 'Adi Mulyanto', 1, 'adi-mulyanto-oyhoeknf', 80),
(789, 'Fitra Arifiansyah', 1, 'fitra-arifiansyah-fkuohgng', 80),
(790, 'Masayu Leylia Khodra', 1, 'masayu-leylia-khodra-hiurgwlz', 80),
(791, 'Muhammad Zuhri Catur Candra', 1, 'muhammad-zuhri-catur-candra-rahirwgz', 80),
(792, 'Fazat Nur Azizah', 1, 'fazat-nur-azizah-oulmmauy', 80),
(793, 'Gusti Ayu Putri Saptawati Soekidjo', 1, 'gusti-ayu-putri-saptawati-soekidjo-mehfotsh', 80),
(794, 'Nugraha Priya Utama', 1, 'nugraha-priya-utama-qcbruofe', 80),
(795, 'Robithoh Annur', 1, 'robithoh-annur-vbtjtrtr', 80),
(796, 'Agung Dewandaru', 1, 'agung-dewandaru-bzotrwva', 80),
(797, 'Fadhil Hidayat', 1, 'fadhil-hidayat-sxppzwge', 81),
(798, 'Dyah Rakhma Aryanti', 1, 'dyah-rakhma-aryanti-tokkxxxb', 81),
(799, 'Umar Khayam', 1, 'umar-khayam-dugxmtae', 81),
(800, 'Bryan Denov', 1, 'bryan-denov-eicmzajk', 81),
(801, 'Haryo Satriyo Tomo', 1, 'haryo-satriyo-tomo-yyiswcba', 81),
(802, 'Ediansjah Zulkifli', 1, 'ediansjah-zulkifli-ecwrrziu', 81),
(803, 'Patria Kusumaningrum', 1, 'patria-kusumaningrum-fbeyrgwo', 81),
(804, 'Muhammad Sonny Abfertiawan', 1, 'muhammad-sonny-abfertiawan-ckhvywjm', 81),
(805, 'Eddy Rachman Gandanegara', 1, 'eddy-rachman-gandanegara-vklrvzeg', 81),
(806, 'Eko Charnius Ilman', 1, 'eko-charnius-ilman-mfyqwpku', 81),
(807, 'I Made Astina', 1, 'i-made-astina-ehuorpyo', 81),
(808, 'Pramudita Satria Palar', 1, 'pramudita-satria-palar-layeuwim', 81),
(809, 'Gea Fardias Mumin', 1, 'gea-fardias-mumin-twgfhxou', 81),
(810, 'Heru Wibowo Poerbo', 1, 'heru-wibowo-poerbo-vcaxpksi', 81),
(811, 'Asep Darmana', 1, 'asep-darmana-fxiywtwd', 81),
(812, 'Aswin Indraprastha', 1, 'aswin-indraprastha-egqkiqlh', 81),
(813, 'Adiwan Fahlan Aritenang', 1, 'adiwan-fahlan-aritenang-uscuyewd', 81),
(814, 'Adenantera Dwicaksono', 1, 'adenantera-dwicaksono-piwfqwpv', 81),
(815, 'Willy Himawan', 1, 'willy-himawan-vrfevaas', 81),
(816, 'Chandra Tresnadi', 1, 'chandra-tresnadi-maudyheb', 81),
(817, 'Slamet Riyadi', 1, 'slamet-riyadi-tbhqdecv', 81),
(818, 'Yogie Candra Bhumi', 1, 'yogie-candra-bhumi-efvxleks', 81),
(819, 'Yuanita Handayati', 1, 'yuanita-handayati-ienswcft', 81),
(820, 'Noorhan Firdaus Pambudi', 1, 'noorhan-firdaus-pambudi-kktcsokb', 81),
(821, 'Akbar Adhi Utama', 1, 'akbar-adhi-utama-syljaepz', 81),
(822, 'Ilma Aulia Zaim', 1, 'ilma-aulia-zaim-cijkokiy', 81),
(823, 'Yuliani Dwi Lestari', 1, 'yuliani-dwi-lestari-vcszgsxh', 81),
(824, 'Marla Setiawati', 1, 'marla-setiawati-hdnqzwrl', 81),
(825, 'Nur Budi Mulyono', 1, 'nur-budi-mulyono-godarrrl', 81),
(826, 'Viek Prayoga Pratama', 1, 'viek-prayoga-pratama-fzjjnmkb', 81),
(827, 'Liane Okdinawati', 1, 'liane-okdinawati-kzcixufx', 81),
(828, 'Eko Agus Prasetio', 1, 'eko-agus-prasetio-ebfddwcy', 81),
(829, 'Poetro Lebdo Sambegoro', 1, 'poetro-lebdo-sambegoro-yzvwcgnj', 81),
(830, 'Javensius Sembiring', 1, 'javensius-sembiring-exeaauqw', 81),
(831, 'Arief Sudradjat', 1, 'arief-sudradjat-sgbddxnn', 81),
(832, 'Peni Astrini Notodarmojo', 1, 'peni-astrini-notodarmojo-vmwsnrdi', 81),
(833, 'Layung Anindya Prasetyanti', 1, 'layung-anindya-prasetyanti-xqzueyag', 81),
(834, 'Erlangga Mahardika', 1, 'erlangga-mahardika-daitaijw', 81),
(835, 'Mursyid Hasan Basri', 1, 'mursyid-hasan-basri-dlbjaobm', 81),
(836, 'Mochammad Chaerul', 1, 'mochammad-chaerul-ldovcmlt', 81),
(837, 'Taufiq Suryo Nugroho', 1, 'taufiq-suryo-nugroho-ahynjdrq', 81),
(838, 'Yuamar Imarrazan Basarah', 1, 'yuamar-imarrazan-basarah-qkeeigfc', 81),
(839, 'Hamonangan Situmorang', 1, 'hamonangan-situmorang-hejeokzx', 81),
(840, 'Isa Anshori', 1, 'isa-anshori-ebudkqbb', 81),
(841, 'Hadi Kardhana', 1, 'hadi-kardhana-bppifejg', 81),
(842, 'Faizal Immaddudin Wira Rohmat', 1, 'faizal-immaddudin-wira-rohmat-mcycbecm', 81),
(843, 'Hafiz Aziz Ahmad', 1, 'hafiz-aziz-ahmad-crkqsjeg', 81),
(844, 'Agustiana', 1, 'agustiana-xflwaksi', 81),
(845, 'Hadi Nurtjahjo', 1, 'hadi-nurtjahjo-qbpzjdor', 81),
(846, 'Tri Hasdianto', 1, 'tri-hasdianto-ncuumpfk', 81),
(847, 'Agus Purwadi', 1, 'agus-purwadi-qrctiwyn', 82),
(848, 'Jihad Furqani', 1, 'jihad-furqani-wjlnzeky', 82),
(849, 'Deny Hamdani', 1, 'deny-hamdani-jkbdiohr', 82),
(850, 'Burhanuddin Halimi', 1, 'burhanuddin-halimi-qmbrxoww', 82),
(851, 'Isnuwardianto', 1, 'isnuwardianto-gocrrgty', 82),
(852, 'Syarif Hidayat', 1, 'syarif-hidayat-nikfjmta', 82),
(853, 'Andriyan Bayu Suksmono', 1, 'andriyan-bayu-suksmono-sgnqovxn', 83),
(854, 'Nana Rachmana Syambas', 1, 'nana-rachmana-syambas-udgpqotc', 83),
(855, 'Aldo Agusdian', 1, 'aldo-agusdian-ntcszvaq', 83),
(856, 'Ian Josef Matheus Edward', 1, 'ian-josef-matheus-edward-oabsyenr', 83),
(857, 'Mohammad Ridwan Effendi', 1, 'mohammad-ridwan-effendi-itrxvpra', 83),
(858, 'Eueung Mulyana', 1, 'eueung-mulyana-uovnnbdz', 83),
(859, 'Mohammad Sigit Arifianto', 1, 'mohammad-sigit-arifianto-pmlqrgkm', 83),
(860, 'Chairunnisa', 1, 'chairunnisa-pihbzqby', 83),
(861, 'Irma Zakia', 1, 'irma-zakia-cphgrgjb', 83),
(862, 'Iskandar', 1, 'iskandar-ittgtiwz', 83),
(863, 'Tutun Juhana', 1, 'tutun-juhana-ypbgdhuw', 83),
(864, 'Effrina Yanti Hamid', 1, 'effrina-yanti-hamid-pnveliok', 83),
(865, 'Adit Kurniawan', 1, 'adit-kurniawan-rxtdvtzm', 83),
(866, 'Sigit Haryadi', 1, 'sigit-haryadi-tgvogxue', 83),
(867, 'Hendrawan', 1, 'hendrawan-itpzkxvx', 83),
(868, 'I Gusti Bagus Baskara Nugraha', 1, 'i-gusti-bagus-baskara-nugraha-jdlsnlab', 84),
(869, 'Suhardi', 1, 'suhardi-ondxulmk', 84),
(870, 'Yusep Rosmansyah', 1, 'yusep-rosmansyah-mghrdepq', 84),
(871, 'Kridanto Surendro', 1, 'kridanto-surendro-eiddgnmw', 84),
(872, 'Suhono Harso Supangkat', 1, 'suhono-harso-supangkat-eawwqhlf', 84),
(873, 'Arry Akhmad Arman', 1, 'arry-akhmad-arman-uakeklpw', 84),
(874, 'Budi Rahardjo', 1, 'budi-rahardjo-jqdvzazi', 84),
(875, 'Donny Danudirdjo', 1, 'donny-danudirdjo-jkbwdihn', 85),
(876, 'Widyawardana Adiprawita', 1, 'widyawardana-adiprawita-dshfvuba', 85),
(877, 'Hasballah Zakaria', 1, 'hasballah-zakaria-lbknplfy', 85),
(878, 'Sarwono Sutikno', 1, 'sarwono-sutikno-euvxzlro', 86),
(879, 'Jaka Sembiring', 1, 'jaka-sembiring-yngvlzaa', 86),
(880, 'Benhard Sitohang', 1, 'benhard-sitohang-fvvkzfhl', 87),
(881, 'Nur Ahmadi', 1, 'nur-ahmadi-fnjckzni', 87),
(882, 'Firman Bagja Juangsa', 1, 'firman-bagja-juangsa-motxndhd', 89),
(883, 'Sandro Mihradi', 1, 'sandro-mihradi-dwyjpewj', 89),
(884, 'Rianto Adhy Sasongko', 1, 'rianto-adhy-sasongko-ylapoact', 89),
(885, 'Mardiyati', 1, 'mardiyati-dpndnlck', 89),
(886, 'Indria Herman', 1, 'indria-herman-yigxmlqf', 89),
(887, 'Satrio Wicaksono', 1, 'satrio-wicaksono-pzakgehg', 89),
(888, 'Djarot Widagdo', 1, 'djarot-widagdo-sbsckyzx', 89),
(889, 'Ignatius Pulung Nurprasetio', 1, 'ignatius-pulung-nurprasetio-zqprxela', 89),
(890, 'Agung Wibowo', 1, 'agung-wibowo-cofdihzt', 89),
(891, 'Bentang Arief Budiman', 1, 'bentang-arief-budiman-peevbwfb', 89),
(892, 'Yunendar Aryo Handoko', 1, 'yunendar-aryo-handoko-gweaxnas', 89),
(893, 'Arief Hariyanto', 1, 'arief-hariyanto-ypvhlcfr', 89),
(894, 'Toto Hardianto', 1, 'toto-hardianto-czohuqqj', 89),
(895, 'Vani Virdyawan', 1, 'vani-virdyawan-avjtcxfe', 89),
(896, 'Taufiq Mulyanto', 1, 'taufiq-mulyanto-cracnfbe', 89),
(897, 'Untung Ari Wibowo', 1, 'untung-ari-wibowo-sgqcoqkr', 89),
(898, 'Nathanael Panagung Tandian', 1, 'nathanael-panagung-tandian-ytntusiy', 89),
(899, 'Hendi Riyanto', 1, 'hendi-riyanto-mkplzuxo', 89),
(900, 'Pandji Prawisudha', 1, 'pandji-prawisudha-jcuyswyt', 89),
(901, 'Budi Heryadi', 1, 'budi-heryadi-imrjywmd', 89),
(902, 'Andi Isra Mahyuddin', 1, 'andi-isra-mahyuddin-zygwdsvg', 89),
(903, 'Tatacipta Dirgantara', 1, 'tatacipta-dirgantara-vxuemwxr', 89),
(904, 'Andi Kuswoyo', 1, 'andi-kuswoyo-mcimnfbx', 89),
(905, 'Ichsan Setya Putra', 1, 'ichsan-setya-putra-akarwrgf', 89),
(906, 'Annisa Jusuf', 1, 'annisa-jusuf-xpwnohsx', 89),
(907, 'Arif Sugiharto', 1, 'arif-sugiharto-rajxpctz', 89),
(908, 'Yuli Setyo Indartono', 1, 'yuli-setyo-indartono-ycnghoem', 89),
(909, 'Husaini Ardy', 1, 'husaini-ardy-qbhfdtqa', 89),
(910, 'Yorina Sarah Franscoise Lantang', 1, 'yorina-sarah-franscoise-lantang-zdbkkuxf', 89),
(911, 'Raden Dadan Ramdan', 1, 'raden-dadan-ramdan-yjfnsejj', 89),
(912, 'Asep Ridwan Setiawan', 1, 'asep-ridwan-setiawan-ocwvgaad', 89),
(913, 'Steven', 1, 'steven-stjnkice', 89),
(914, 'Budi Hartono Setiamarga', 1, 'budi-hartono-setiamarga-bgqkxjju', 89),
(915, 'Ekavianty Prajatelistia', 1, 'ekavianty-prajatelistia-zzfnlujm', 89),
(916, 'Zainal Abidin', 1, 'zainal-abidin-ryrdczhz', 89),
(917, 'Indrawanto', 1, 'indrawanto-atfxhsgl', 89),
(918, 'Bagus Budiwantoro', 1, 'bagus-budiwantoro-bxnftgkt', 89),
(919, 'I Wayan Suweca', 1, 'i-wayan-suweca-dqubaowc', 89),
(920, 'M. Agus Kariem', 1, 'm-agus-kariem-arjjtnrz', 89),
(921, 'Rachman Setiawan', 1, 'rachman-setiawan-zpwncgol', 89),
(922, 'Ari Darmawan Pasek', 1, 'ari-darmawan-pasek-qowlcdqi', 89),
(923, 'Tubagus Ahmad Fauzi Soelaiman', 1, 'tubagus-ahmad-fauzi-soelaiman-zqprjbtl', 89),
(924, 'Priyono Soetikno', 1, 'priyono-soetikno-maitgrkf', 89),
(925, 'I Nengah Diasta', 1, 'i-nengah-diasta-rcculqmy', 89),
(926, 'Tri Prakosa', 1, 'tri-prakosa-ictaxekz', 89),
(927, 'Sri Raharno', 1, 'sri-raharno-atbwrxbc', 89),
(928, 'Yatna Yuwana Martawirya', 1, 'yatna-yuwana-martawirya-ziqpabux', 89),
(929, 'Tri Yuswidjajanto Zaenuri', 1, 'tri-yuswidjajanto-zaenuri-okfnkoae', 89),
(930, 'I Gusti Nyoman Wiratmaja', 1, 'i-gusti-nyoman-wiratmaja-znwkbkkx', 89),
(931, 'Ditho Ardiansyah Pulungan', 1, 'ditho-ardiansyah-pulungan-iltxqqoj', 89),
(932, 'Chakimoelmal Jasjkur', 1, 'chakimoelmal-jasjkur-zesbazxf', 89),
(933, 'Hari Muhammad', 1, 'hari-muhammad-yohibljr', 90),
(934, 'Yazdi Ibrahim Jenie', 1, 'yazdi-ibrahim-jenie-peqnapmo', 90),
(935, 'Lavi Rizki Zuhal', 1, 'lavi-rizki-zuhal-eoykgttr', 90),
(936, 'Luqman Fathurrohim', 1, 'luqman-fathurrohim-hetzgork', 90),
(937, 'Ridanto Eko Poetro', 1, 'ridanto-eko-poetro-evvgyyxh', 90),
(938, 'Leonardo Gunawan', 1, 'leonardo-gunawan-abqyoysn', 90),
(939, 'Muhamad Giri Suada', 1, 'muhamad-giri-suada-imfjyiul', 90),
(940, 'Sigit Puji Santosa', 1, 'sigit-puji-santosa-jswevvof', 90),
(941, 'Mahesa Akbar', 1, 'mahesa-akbar-mnnvpber', 90),
(942, 'Mochammad Agoes Moelyadi', 1, 'mochammad-agoes-moelyadi-utgmuzsd', 90),
(943, 'Ema Amalia', 1, 'ema-amalia-cliltize', 90),
(944, 'Ony Arifianto', 1, 'ony-arifianto-vkyvpkhc', 90),
(945, 'Hendarko', 1, 'hendarko-jroitiic', 90),
(946, 'Hendri Syamsudin', 1, 'hendri-syamsudin-esqajlyo', 90),
(947, 'Rais Zain', 1, 'rais-zain-yxjzsemc', 90),
(948, 'Hisar Manongam Pasaribu', 1, 'hisar-manongam-pasaribu-kzyuoxdq', 90),
(949, 'Khairul Ummah', 1, 'khairul-ummah-vhjaqrpc', 90),
(950, 'Firman Hartono', 1, 'firman-hartono-reiipycw', 90),
(951, 'Edy Suwondo', 1, 'edy-suwondo-tnnzwech', 90),
(952, 'Mahardi Sadono', 1, 'mahardi-sadono-nochagbb', 90),
(953, 'Toto Indriyanto', 1, 'toto-indriyanto-rmpmbtpm', 90),
(954, 'Bambang Kismono Hadi', 1, 'bambang-kismono-hadi-mlxeefro', 90),
(955, 'Seno Sahisnu Rawikara', 1, 'seno-sahisnu-rawikara-gdwvrcjj', 90),
(956, 'Muhammad Kusni', 1, 'muhammad-kusni-smwkzxuh', 90),
(957, 'Yohanes Bimo Dwianto', 1, 'yohanes-bimo-dwianto-yeeuvfqj', 90),
(958, 'Riska Rachmantyo', 1, 'riska-rachmantyo-xqtvzhcx', 91),
(959, 'Arif Basuki', 1, 'arif-basuki-jflffgrp', 91),
(960, 'Hermawan Judawisastra', 1, 'hermawan-judawisastra-qcirhpyy', 91),
(961, 'Riza Wirawan', 1, 'riza-wirawan-qsxihpfy', 91),
(962, 'Arie Wibowo', 1, 'arie-wibowo-yqirdqil', 91),
(963, 'Lia Amelia Tresna Wulan Asri', 1, 'lia-amelia-tresna-wulan-asri-oetjkgdo', 91),
(964, 'Afriyanti Sumboja', 1, 'afriyanti-sumboja-ezwndgot', 91),
(965, 'Biemo Woerjanto Soemardi', 1, 'biemo-woerjanto-soemardi-itqatalx', 92),
(966, 'Izqi Yustina Ammylia Yusuf', 1, 'izqi-yustina-ammylia-yusuf-tiwocgvf', 92),
(967, 'Idwan Santoso', 1, 'idwan-santoso-qfsateuv', 92),
(968, 'Febri Zukhruf', 1, 'febri-zukhruf-zfyrqcdo', 92),
(969, 'Agus Jatnika Effendi', 1, 'agus-jatnika-effendi-saqodqkj', 92),
(970, 'Dyah Wulandari Putri', 1, 'dyah-wulandari-putri-dssxlqoo', 92),
(971, 'Widyaningtias', 1, 'widyaningtias-bqcfrtvm', 92),
(972, 'Jessica Rikanti Tawekal', 1, 'jessica-rikanti-tawekal-zlauimfl', 92),
(973, 'R. Muslinang Moestopo', 1, 'r-muslinang-moestopo-jbslfxji', 92),
(974, 'Muhammad Riyansyah', 1, 'muhammad-riyansyah-glmdnxcn', 92),
(975, 'Ahmad Mukhlis Firdaus', 1, 'ahmad-mukhlis-firdaus-ignakkzc', 92),
(976, 'Ima Fatima', 1, 'ima-fatima-fhzctuyo', 92),
(977, 'Mochamad Prasetiyo Effendi Yasin', 1, 'mochamad-prasetiyo-effendi-yasin-myyrriwb', 92),
(978, 'Annisa Safira Riska', 1, 'annisa-safira-riska-jrcgxqzi', 92),
(979, 'Saut Aritua Hasiholan Sagala', 1, 'saut-aritua-hasiholan-sagala-ehvdqziq', 92),
(980, 'Kukuh Rizki Satriaji', 1, 'kukuh-rizki-satriaji-ifoecvew', 92),
(981, 'Annisa Rahmani Qastharin', 1, 'annisa-rahmani-qastharin-hnzzknyw', 92),
(982, 'Dany Muhammad Athory Ramdlany', 1, 'dany-muhammad-athory-ramdlany-uthyjxrf', 92),
(983, 'Prawira Fajarindra Belgiawan', 1, 'prawira-fajarindra-belgiawan-xgkzvipn', 92),
(984, 'Octaviani Ratnasari Santoso', 1, 'octaviani-ratnasari-santoso-oniyduro', 92),
(985, 'Nur Arief Rahmatsyah Putranto', 1, 'nur-arief-rahmatsyah-putranto-eyidofpb', 92),
(986, 'Uruqul Nadhif Dzakiy', 1, 'uruqul-nadhif-dzakiy-zfzikidh', 92),
(987, 'Fransisca Budyanto Widjaja', 1, 'fransisca-budyanto-widjaja-cmqbhnzb', 92),
(988, 'Achmad Fajar Hendarman', 1, 'achmad-fajar-hendarman-fltowwyw', 92),
(989, 'Irayanti Adriant', 1, 'irayanti-adriant-aadpbzzt', 92),
(990, 'Benno Rahardyan', 1, 'benno-rahardyan-vmxcizul', 92),
(991, 'Ahmad Soleh Setiyawan', 1, 'ahmad-soleh-setiyawan-tpnkvdtn', 92),
(992, 'Dinda Annisa Nurdiani', 1, 'dinda-annisa-nurdiani-okifkwna', 92),
(993, 'Margareth Setiawan', 1, 'margareth-setiawan-lkneinst', 92),
(994, 'Bayuningrat', 1, 'bayuningrat-aqrpuvop', 92),
(995, 'Dematria Pringgabayu', 1, 'dematria-pringgabayu-zbqvhvue', 92),
(996, 'Hanry Kurnia Lasifa', 1, 'hanry-kurnia-lasifa-wtkmwcqo', 92),
(997, 'Bagas Dwipantara Putra', 1, 'bagas-dwipantara-putra-yconeehx', 92),
(998, 'Sabrina Ilma Sakina', 1, 'sabrina-ilma-sakina-asmltaft', 92),
(999, 'Aris Aryanto', 1, 'aris-aryanto-srocsbnc', 99),
(1000, 'Dyah Kusumastuti', 1, 'dyah-kusumastuti-ceuyhore', 99),
(1001, 'Ivan Sandi Darma', 1, 'ivan-sandi-darma-shlmfsxb', 99),
(1002, 'Indra Djati', 1, 'indra-djati-dkwgwrbj', 99),
(1003, 'Adang Surahman', 1, 'adang-surahman-fzzjjruu', 99),
(1004, 'Rizal Z. Tamin', 1, 'rizal-z-tamin-qbhbjjbs', 99),
(1005, 'Hernawan Mahfudz', 1, 'hernawan-mahfudz-bkldegfi', 99),
(1006, 'Sugeng Krisnanto', 1, 'sugeng-krisnanto-vpyrdxjx', 99),
(1007, 'Cahyono', 1, 'cahyono-hzxgjvsu', 99),
(1008, 'Mohammad Bagus Adityawan', 1, 'mohammad-bagus-adityawan-ndhomjgt', 99),
(1009, 'Sindur P. Mangkoesoebroto', 1, 'sindur-p-mangkoesoebroto-yxolninj', 99),
(1010, 'Prasanti Widyasih Sarli', 1, 'prasanti-widyasih-sarli-rxrxkhrx', 99),
(1011, 'Sigit Darmawan', 1, 'sigit-darmawan-mkgflntt', 99),
(1012, 'Made Suarjana', 1, 'made-suarjana-twpntsxb', 99),
(1013, 'Herlien Dwiarti Soemari', 1, 'herlien-dwiarti-soemari-akbgecey', 99),
(1014, 'Erza Rismantojo', 1, 'erza-rismantojo-khnnkvzp', 99),
(1015, 'Muhammad Syahril Badri Kusuma', 1, 'muhammad-syahril-badri-kusuma-qyzdfgim', 99),
(1016, 'Eka Oktariyanto Nugroho', 1, 'eka-oktariyanto-nugroho-flcjrovg', 99),
(1017, 'Dhemi Harlan', 1, 'dhemi-harlan-nrholshq', 99),
(1018, 'Joko Nugroho', 1, 'joko-nugroho-xdbvyeqp', 99),
(1019, 'Harun Al Rasyid', 1, 'harun-al-rasyid-hnxxpuyc', 99),
(1020, 'Rudy Hermawan Karsaman', 1, 'rudy-hermawan-karsaman-eowyfuoe', 99),
(1021, 'Ade Sjafruddin', 1, 'ade-sjafruddin-ilglmffp', 99),
(1022, 'Erwin Lim', 1, 'erwin-lim-wvglppis', 99),
(1023, 'Iswandi Imran', 1, 'iswandi-imran-aruxklwj', 99),
(1024, 'I Wayan Sengara', 1, 'i-wayan-sengara-qqwumwop', 99),
(1025, 'Andhika Sahadewa', 1, 'andhika-sahadewa-utdftoyw', 99),
(1026, 'Hasbullah Nawir', 1, 'hasbullah-nawir-tkdayenq', 99),
(1027, 'Sri Legowo Wignyo Darsono', 1, 'sri-legowo-wignyo-darsono-nbdqdwyv', 99),
(1028, 'Yadi Suryadi', 1, 'yadi-suryadi-awqqvsfa', 99),
(1029, 'Ana Nurganah Chaidar', 1, 'ana-nurganah-chaidar-qimzyadq', 99),
(1030, 'Nurul Wahjuningsih', 1, 'nurul-wahjuningsih-mfowrsfu', 99),
(1031, 'Russ Bona Frazila', 1, 'russ-bona-frazila-fjoqfwjq', 99),
(1032, 'R. Sony Sulaksono Wibowo', 1, 'r-sony-sulaksono-wibowo-etzeksrz', 99),
(1033, 'Nasuhi Zain', 1, 'nasuhi-zain-vuknmrre', 99),
(1034, 'Puti Farida Marzuki', 1, 'puti-farida-marzuki-mooebtsn', 99),
(1035, 'Meifrinaldi', 1, 'meifrinaldi-dhpiozey', 99),
(1036, 'Eliza Rosmaya Puri', 1, 'eliza-rosmaya-puri-tdnsnpwa', 99),
(1037, 'Iris Mahani', 1, 'iris-mahani-unbmomzd', 99),
(1038, 'Krishna Suryanto', 1, 'krishna-suryanto-glkewszi', 99),
(1039, 'Budi Hasiholan', 1, 'budi-hasiholan-ljqeocps', 99),
(1040, 'Rani Gayatri Kusumawardhani P.', 1, 'rani-gayatri-kusumawardhani-p-nfhfpnbc', 99),
(1041, 'Masyhur Irsyam', 1, 'masyhur-irsyam-guiijlay', 99),
(1042, 'Dedi Apriadi', 1, 'dedi-apriadi-mwlonihx', 99),
(1043, 'Agung Wiyono Hadi Soeharno', 1, 'agung-wiyono-hadi-soeharno-fpqjgauv', 99),
(1044, 'Widyarini Weningtyas', 1, 'widyarini-weningtyas-hxfiovdg', 99),
(1045, 'Harmein Rahman', 1, 'harmein-rahman-occxgidt', 99),
(1046, 'Eri Susanto Hariyadi', 1, 'eri-susanto-hariyadi-jyejzhns', 99),
(1047, 'Jongga Jihanny', 1, 'jongga-jihanny-bxftpjft', 99),
(1048, 'Aine Kusumawati', 1, 'aine-kusumawati-coemajjk', 99),
(1049, 'Endra Susila', 1, 'endra-susila-avrcidel', 99),
(1050, 'Dantje Kardana Natakusumah', 1, 'dantje-kardana-natakusumah-odrodsut', 99),
(1051, 'Bambang Sugeng Subagio', 1, 'bambang-sugeng-subagio-ltlsmkqd', 99),
(1052, 'James Nobelia Isnania Wardhana', 1, 'james-nobelia-isnania-wardhana-yrgxuvvd', 100),
(1053, 'Nadiyatur Rahmatikal Wasiah', 1, 'nadiyatur-rahmatikal-wasiah-vkimmqor', 100),
(1054, 'Teddy Tedjakusuma', 1, 'teddy-tedjakusuma-habxdaok', 100),
(1055, 'Adyati Pradini Yudison', 1, 'adyati-pradini-yudison-rclhjpcn', 100),
(1056, 'Mindriany Syafila', 1, 'mindriany-syafila-srpeticp', 100),
(1057, 'Mayrina Firdayati', 1, 'mayrina-firdayati-usrkutvu', 100),
(1058, 'Dwina Roosmini', 1, 'dwina-roosmini-hrtjqoeh', 100),
(1059, 'Mariana Marselina S.', 1, 'mariana-marselina-s-pggpjbau', 100),
(1060, 'Kania Dewi', 1, 'kania-dewi-rxhxeuui', 100),
(1061, 'Asep Sofyan', 1, 'asep-sofyan-pnpwrvpx', 100),
(1062, 'Marisa Handajani', 1, 'marisa-handajani-yldxfafr', 100),
(1063, 'Moh. Irsyad', 1, 'moh-irsyad-gapjolvf', 100),
(1064, 'Sukandar', 1, 'sukandar-fykhztgj', 100),
(1065, 'Suharyanto', 1, 'suharyanto-zojadwre', 100),
(1066, 'Katharina Oginawati', 1, 'katharina-oginawati-ldabnnxb', 100),
(1067, 'Nurul Chazanah', 1, 'nurul-chazanah-qtgsewud', 100),
(1068, 'Anindrya Nastiti', 1, 'anindrya-nastiti-crobshib', 100),
(1069, 'Indah Rachmatiah Siti Salami', 1, 'indah-rachmatiah-siti-salami-yhttacba', 100),
(1070, 'Rofiq Iqbal', 1, 'rofiq-iqbal-jiqkrtbw', 100),
(1071, 'Edwan Kardena', 1, 'edwan-kardena-hhmfzqxr', 100),
(1072, 'Barti Setiani Muntalif', 1, 'barti-setiani-muntalif-vcoitpjt', 100),
(1073, 'I Made Wahyu Widyarsana', 1, 'i-made-wahyu-widyarsana-crxfbrcb', 100),
(1074, 'Yuniati', 1, 'yuniati-rxvlpalt', 100),
(1075, 'Suprihanto', 1, 'suprihanto-twundxhg', 100),
(1076, 'Herto Dwi Ariesyady', 1, 'herto-dwi-ariesyady-zzzydust', 100),
(1077, 'Puji Lestari', 1, 'puji-lestari-mnurtwzm', 100),
(1078, 'Windy Iriana', 1, 'windy-iriana-ufqneaxr', 100),
(1079, 'Emenda Sembiring', 1, 'emenda-sembiring-fvltfznt', 100),
(1080, 'Qomarudin Helmy', 1, 'qomarudin-helmy-wtbhrbfn', 100),
(1081, 'Opy Kurniasari', 1, 'opy-kurniasari-yguziwgg', 100),
(1082, 'Dady Surachman', 1, 'dady-surachman-jrvrbwsm', 100),
(1083, 'Prayatni Soewondo', 1, 'prayatni-soewondo-iyfqfcyw', 100),
(1084, 'Raden Driejana', 1, 'raden-driejana-xescdjjn', 100),
(1085, 'Suci Wulandari', 1, 'suci-wulandari-cokcffek', 100),
(1086, 'Ridwan Fauzi', 1, 'ridwan-fauzi-qkerpmcf', 100),
(1087, 'Harman Ajiwibowo', 1, 'harman-ajiwibowo-oduvsopt', 101),
(1088, 'Alamsyah Kurniawan', 1, 'alamsyah-kurniawan-tayicqrz', 101),
(1089, 'Muslim Muin', 1, 'muslim-muin-zbgvgsjl', 101),
(1090, 'Entin Agustini Karjadi', 1, 'entin-agustini-karjadi-fdjaesis', 101),
(1091, 'Rildova', 1, 'rildova-gkblpjrr', 101),
(1092, 'Sri Murti Adiyastuti', 1, 'sri-murti-adiyastuti-sjhjghkk', 101),
(1093, 'Paramashanti', 1, 'paramashanti-erywjebp', 101),
(1094, 'Hendriyawan', 1, 'hendriyawan-rvbfswlu', 101),
(1095, 'Andojo Wurjanto', 1, 'andojo-wurjanto-khvfaysp', 101),
(1096, 'Hendra Achiari', 1, 'hendra-achiari-cxilybyv', 101),
(1097, 'Krisnaldi', 1, 'krisnaldi-ewzxljds', 101),
(1098, 'Irsan Soemantri Brodjonegoro', 1, 'irsan-soemantri-brodjonegoro-rgnramig', 101),
(1099, 'Farid Putra Bakti', 1, 'farid-putra-bakti-rxseawfa', 101),
(1100, 'Nita Yuanita', 1, 'nita-yuanita-ttkolkbo', 101),
(1101, 'Ricky Lukman Tawekal', 1, 'ricky-lukman-tawekal-urkmtahd', 101),
(1102, 'Lurohman Mamin Masturi', 1, 'lurohman-mamin-masturi-gltbeooo', 101),
(1103, 'Andri Gumilar', 1, 'andri-gumilar-nykhukhj', 102),
(1104, 'Muhamad Abduh', 1, 'muhamad-abduh-uqakyqfa', 105),
(1105, 'Djunaedi Kosasih', 1, 'djunaedi-kosasih-jiyvvqkk', 105),
(1106, 'Arwin', 1, 'arwin-wpmviazz', 106),
(1107, 'Sri Maryati', 1, 'sri-maryati-kqagpcpq', 108),
(1108, 'Tubagus Muhammad Aziz Soelaiman', 1, 'tubagus-muhammad-aziz-soelaiman-edxtskjq', 113),
(1109, 'Erika Yuni Astuti', 1, 'erika-yuni-astuti-btcxqfpk', 113),
(1110, 'Benedictus Kombaitan', 1, 'benedictus-kombaitan-qgomsmwx', 113),
(1111, 'Binsar Parasian Naipospos', 1, 'binsar-parasian-naipospos-fmsyshoe', 113),
(1112, 'Miming Miharja', 1, 'miming-miharja-mdbonuqv', 113),
(1113, 'Iwan Kustiwan', 1, 'iwan-kustiwan-wskjxwti', 113),
(1114, 'Firmansyah', 1, 'firmansyah-mqjytfif', 113),
(1115, 'Rr. Diah Asih Purwaningrum', 1, 'rr-diah-asih-purwaningrum-hmjuowqw', 113),
(1116, 'Permana', 1, 'permana-kzxbszwa', 113),
(1117, 'Lily Tambunan', 1, 'lily-tambunan-tevnescn', 113),
(1118, 'Surjamanto W.', 1, 'surjamanto-w-bpzdotbw', 113),
(1119, 'Mochamad Donny Koerniawan', 1, 'mochamad-donny-koerniawan-vxkaoinz', 113),
(1120, 'Andry Widyowijatnoko', 1, 'andry-widyowijatnoko-nfazrqnr', 113),
(1121, 'Dewi Larasati', 1, 'dewi-larasati-vdvtbptd', 113),
(1122, 'Robby Dwiko Juliardi', 1, 'robby-dwiko-juliardi-xswuhbno', 113),
(1123, 'Dibya Kusyala', 1, 'dibya-kusyala-wbmofcsr', 113),
(1124, 'Indah Widiastuti', 1, 'indah-widiastuti-miuahlhx', 113),
(1125, 'Christina Gantini', 1, 'christina-gantini-ahpnbbcb', 113),
(1126, 'Tri Yuwono', 1, 'tri-yuwono-ashcdlyl', 113),
(1127, 'Mohammad Jehansyah Siregar', 1, 'mohammad-jehansyah-siregar-huriscrf', 113),
(1128, 'Endang Triningsih Soetrisno', 1, 'endang-triningsih-soetrisno-fanjmzhi', 113),
(1129, 'Medria Shekar Rani', 1, 'medria-shekar-rani-lnenjrzm', 113),
(1130, 'Allis Nurdini', 1, 'allis-nurdini-ieadjwwh', 113),
(1131, 'Bambang Setia Budi', 1, 'bambang-setia-budi-pycfyfzc', 113),
(1132, 'Wiwik Dwi Pratiwi', 1, 'wiwik-dwi-pratiwi-kpjcntni', 113),
(1133, 'Budi Faisal', 1, 'budi-faisal-vbnqyyzy', 113),
(1134, 'Agus Suharjono Ekomadyo', 1, 'agus-suharjono-ekomadyo-hdorulws', 113),
(1135, 'Mohammad Zaini Dahlan', 1, 'mohammad-zaini-dahlan-mslaryfv', 113),
(1136, 'Achmad Deni Tardiyana', 1, 'achmad-deni-tardiyana-rskyodco', 113),
(1137, 'Widiyani', 1, 'widiyani-swjirbze', 113),
(1138, 'Hanson Endra Kusuma', 1, 'hanson-endra-kusuma-mefgpqyo', 113),
(1139, 'Woerjantari Kartidjo', 1, 'woerjantari-kartidjo-hejxegtp', 113),
(1140, 'Agustinus Adib Abadi', 1, 'agustinus-adib-abadi-viwqeoxe', 113),
(1141, 'Fauzan Alfi Agirachman', 1, 'fauzan-alfi-agirachman-ldmslzyb', 113),
(1142, 'Samsirina', 1, 'samsirina-dxmvhsjy', 113),
(1143, 'Widjaja Martokusumo', 1, 'widjaja-martokusumo-hvbmhtau', 113),
(1144, 'Arief Rosyidie', 1, 'arief-rosyidie-aumqdgno', 114),
(1145, 'Ibnu Syabri', 1, 'ibnu-syabri-znmtwkla', 114),
(1146, 'Fikri Zul Fahmi', 1, 'fikri-zul-fahmi-hfzttlua', 114),
(1147, 'Nurrohman Wijaya', 1, 'nurrohman-wijaya-sybnhssn', 114),
(1148, 'Wilmar A. Salim', 1, 'wilmar-a-salim-dbqxdwyn', 114),
(1149, 'Rintakasari Vitri Ayuningtyas', 1, 'rintakasari-vitri-ayuningtyas-pfrztuux', 114),
(1150, 'Subarkah', 1, 'subarkah-obshigqh', 114),
(1151, 'Tengku Munawar Chalil', 1, 'tengku-munawar-chalil-swtnucqc', 114),
(1152, 'Lanthika Atianta', 1, 'lanthika-atianta-vshgijgs', 114),
(1153, 'Pradono', 1, 'pradono-jqbrddnu', 114),
(1154, 'Pringgo Dwiyantoro', 1, 'pringgo-dwiyantoro-hvhlnjxk', 114),
(1155, 'Siti Herni Rochana', 1, 'siti-herni-rochana-ekmabigy', 114),
(1156, 'Harkunti Pertiwi Rahayu', 1, 'harkunti-pertiwi-rahayu-dkwjdcxk', 114),
(1157, 'Ridwan Sutriadi', 1, 'ridwan-sutriadi-gjoalqem', 114),
(1158, 'Maya Safira', 1, 'maya-safira-pxjtprrh', 114),
(1159, 'Haryo Winarso', 1, 'haryo-winarso-fsronxdg', 114),
(1160, 'Tubagus Furqon Sofhani', 1, 'tubagus-furqon-sofhani-xyyfjzsh', 114),
(1161, 'Suhirman', 1, 'suhirman-sksymyxj', 114),
(1162, 'Isnu Putra Pratama', 1, 'isnu-putra-pratama-fnhkhgns', 114),
(1163, 'RM. Petrus Natalivan Indradjati', 1, 'rm-petrus-natalivan-indradjati-cdkgtmfp', 114),
(1164, 'Niken Prilandita', 1, 'niken-prilandita-xfuyulvo', 114),
(1165, 'Denny Zulkaidi', 1, 'denny-zulkaidi-itcuzlix', 114),
(1166, 'Happy Pebruman Fadjaruddin Amalputra', 1, 'happy-pebruman-fadjaruddin-amalputra-pnwyncyj', 114),
(1167, 'Shanty Yulianti Rachmat', 1, 'shanty-yulianti-rachmat-awzrlszv', 114),
(1168, 'Maman Suryaman', 1, 'maman-suryaman-yohxugki', 114),
(1169, 'I Gusti Ayu Andani', 1, 'i-gusti-ayu-andani-bxndweuq', 114),
(1170, 'Andi Oetomo', 1, 'andi-oetomo-bekrydto', 114),
(1171, 'Munadjat', 1, 'munadjat-qgyvtcta', 114),
(1172, 'Teti Armiati Argo', 1, 'teti-armiati-argo-juvtypvy', 114),
(1173, 'Heru Purboyo Hidayat Putro', 1, 'heru-purboyo-hidayat-putro-itfwrfuj', 114),
(1174, 'Sugiyantoro', 1, 'sugiyantoro-zaqmaisb', 114),
(1175, 'Puspita Dirgahayani', 1, 'puspita-dirgahayani-kijhrsdm', 114),
(1176, 'Delik Hudalah', 1, 'delik-hudalah-onvpjkrs', 114),
(1177, 'Ninik Suhartini', 1, 'ninik-suhartini-kanzvkih', 114),
(1178, 'Sonny Yuliar', 1, 'sonny-yuliar-ozuujkqp', 114),
(1179, 'Gatot Yudoko', 1, 'gatot-yudoko-pweoluvv', 116),
(1180, 'Sugeng Triyadi S.', 1, 'sugeng-triyadi-s-subnobnn', 117),
(1181, 'Kartib Bayu', 1, 'kartib-bayu-vpnzcwri', 118),
(1182, 'Himasari Hanan', 1, 'himasari-hanan-ggyngwlw', 119),
(1183, 'Iwan Sudradjat', 1, 'iwan-sudradjat-idhwegvv', 123),
(1184, 'Irma Damajanti', 1, 'irma-damajanti-hhpwwkop', 125),
(1185, 'Almira Belinda Zainsjah', 1, 'almira-belinda-zainsjah-bxkephec', 125),
(1186, 'Ifa Safira Mustikadara', 1, 'ifa-safira-mustikadara-aardypqi', 125),
(1187, 'Oco Santoso', 1, 'oco-santoso-lzsrtydl', 125),
(1188, 'Dwi Hatmojo Danurdoro', 1, 'dwi-hatmojo-danurdoro-npoaunlk', 125),
(1189, 'Tendy Yulisca Ramadin', 1, 'tendy-yulisca-ramadin-hsbootwx', 125),
(1190, 'Muksin', 1, 'muksin-ifqbgguh', 125),
(1191, 'Dona Saphiranti', 1, 'dona-saphiranti-acstnoqi', 125),
(1192, 'Imam Damar Djati', 1, 'imam-damar-djati-sxcxpjyi', 125),
(1193, 'Dody Achmad Nawawi S.S.', 1, 'dody-achmad-nawawi-ss-bnpmigab', 125),
(1194, 'Zusfa Roihan', 1, 'zusfa-roihan-ajnzywcl', 125),
(1195, 'Dadang Sudrajat', 1, 'dadang-sudrajat-qoyyzztk', 125),
(1196, 'Mutiara Ayu Larasati', 1, 'mutiara-ayu-larasati-yjdphoia', 125),
(1197, 'Hatif Adiar Almantara', 1, 'hatif-adiar-almantara-mtbdzgus', 125),
(1198, 'Radi Arwinda', 1, 'radi-arwinda-ksrcfthp', 125),
(1199, 'Zaini Rais', 1, 'zaini-rais-bdlwegwe', 125),
(1200, 'Irfansyah', 1, 'irfansyah-gdhuzlle', 125),
(1201, 'Hendhy Nansha', 1, 'hendhy-nansha-whyzehrd', 125),
(1202, 'Firmanda Satria', 1, 'firmanda-satria-kgdwukoz', 125),
(1203, 'Michael Binuko Sri Herawan', 1, 'michael-binuko-sri-herawan-onektdww', 125),
(1204, 'Budi Adi Nugroho', 1, 'budi-adi-nugroho-gvdkbpyd', 125),
(1205, 'Arianti Ayu Puspita', 1, 'arianti-ayu-puspita-kjxdqlyj', 125),
(1206, 'Nedina Sari', 1, 'nedina-sari-lvyidrsd', 125),
(1207, 'Nurdian Ichsan', 1, 'nurdian-ichsan-jlcuhivx', 125),
(1208, 'Intan Prameswari', 1, 'intan-prameswari-jlbsglpt', 125),
(1209, 'Etika Vidyarini', 1, 'etika-vidyarini-jgyitikz', 125),
(1210, 'Miranti Sari Rahma', 1, 'miranti-sari-rahma-jxdaolpb', 125),
(1211, 'Natas Setiabudhi Daryono Putra', 1, 'natas-setiabudhi-daryono-putra-oexgzygh', 125),
(1212, 'Prananda Luffiansyah Malasan', 1, 'prananda-luffiansyah-malasan-edkhwgdc', 125),
(1213, 'Banung Grahita', 1, 'banung-grahita-iscgmjff', 125),
(1214, 'Ardhana Riswarie', 1, 'ardhana-riswarie-xellaffb', 125),
(1215, 'Muhammad Ihsan D.R.S.A.S.', 1, 'muhammad-ihsan-drsas-weqkoigy', 125),
(1216, 'Dikdik Sayahdikumullah', 1, 'dikdik-sayahdikumullah-igzssflk', 125),
(1217, 'Triyadi Guntur Wiratmo', 1, 'triyadi-guntur-wiratmo-lczodxul', 125),
(1218, 'Tisna', 1, 'tisna-jesfjvap', 126),
(1219, 'Duto Hardono', 1, 'duto-hardono-navecvjc', 126),
(1220, 'Nuning Yanti Damayanti', 1, 'nuning-yanti-damayanti-mbxeojbc', 126),
(1221, 'Kiki Rizky Soetisna Putri', 1, 'kiki-rizky-soetisna-putri-mzuhpxql', 126),
(1222, 'Andryanto Rikrik Kusmara', 1, 'andryanto-rikrik-kusmara-iueqiaps', 126),
(1223, 'Patriot Mukmin', 1, 'patriot-mukmin-hniiwiaj', 126),
(1224, 'Deden Hendan Durahman', 1, 'deden-hendan-durahman-vixgivuy', 126),
(1225, 'Danuh Tyas Pradipta', 1, 'danuh-tyas-pradipta-yiszzgsq', 126),
(1226, 'Ira Adriati', 1, 'ira-adriati-xzeezkqd', 126),
(1227, 'Agung Hujatnika', 1, 'agung-hujatnika-fozluchf', 126),
(1228, 'Rizki Akhmad Zaelani Harry', 1, 'rizki-akhmad-zaelani-harry-ytayleri', 126),
(1229, 'Asmudjo Jono Irianto', 1, 'asmudjo-jono-irianto-mpgtpwoz', 126),
(1230, 'John Martono', 1, 'john-martono-dbvggtsl', 127),
(1231, 'Yan Yan Sunarya', 1, 'yan-yan-sunarya-ideflwow', 127),
(1232, 'Tyar Ratuannisa', 1, 'tyar-ratuannisa-vsgktcba', 127),
(1233, 'Achmad Haldani Destiarmand', 1, 'achmad-haldani-destiarmand-utfvcpzi', 127),
(1234, 'Innamia Indriani', 1, 'innamia-indriani-stpduwbc', 127),
(1235, 'Bintan Titisari', 1, 'bintan-titisari-pnxfodgh', 127),
(1236, 'Kahfiati Kahdar', 1, 'kahfiati-kahdar-lxvdzpwo', 127),
(1237, 'Asyifa Rachmadina Jiniputri', 1, 'asyifa-rachmadina-jiniputri-tdbzkccz', 127),
(1238, 'Gita Winata', 1, 'gita-winata-sbpxegcc', 127),
(1239, 'Akbar Adhi Satrio', 1, 'akbar-adhi-satrio-rqovdtbu', 127),
(1240, 'Dian Widiawati', 1, 'dian-widiawati-yewwugpf', 127),
(1241, 'Nadia Arfan', 1, 'nadia-arfan-kembgsxz', 127),
(1242, 'Ruly Darmawan', 1, 'ruly-darmawan-paykzyot', 128),
(1243, 'Yuni Maharani', 1, 'yuni-maharani-esanhxoy', 128),
(1244, 'Yuki Agriardi Koswara', 1, 'yuki-agriardi-koswara-ewgdnvhb', 128),
(1245, 'Kharista Astrini Sakya', 1, 'kharista-astrini-sakya-cstlstsw', 128),
(1246, 'Gregorius Prasetyo Adhitama', 1, 'gregorius-prasetyo-adhitama-qczhcjzp', 128),
(1247, 'Arsaika Widasati', 1, 'arsaika-widasati-avykyftf', 128),
(1248, 'Yannes Martinus Pasaribu', 1, 'yannes-martinus-pasaribu-aricakuk', 128),
(1249, 'Deny Willy Junaidy', 1, 'deny-willy-junaidy-caywuspf', 128),
(1250, 'Andriyanto Wibisono', 1, 'andriyanto-wibisono-krjthign', 128),
(1251, 'Budi Isdianto', 1, 'budi-isdianto-dtdltppn', 128),
(1252, 'Imam Santosa', 1, 'imam-santosa-hknyaucj', 128),
(1253, 'Bagus Handoko', 1, 'bagus-handoko-ghjptykq', 128),
(1254, 'Bismo Jelantik Joyodiharjo', 1, 'bismo-jelantik-joyodiharjo-wnwnhwoe', 128),
(1255, 'Naomi Haswanto', 1, 'naomi-haswanto-pgujupqo', 129),
(1256, 'Dianing Ratri', 1, 'dianing-ratri-kjcuboim', 129),
(1257, 'Riama Maslan Sihombing', 1, 'riama-maslan-sihombing-ntsqmmdr', 129),
(1258, 'Oki Hamka Suyatna', 1, 'oki-hamka-suyatna-gbildqkb', 129),
(1259, 'Intan Rizky Mutiaz', 1, 'intan-rizky-mutiaz-zizwxoxw', 129),
(1260, 'Hendy Hertiasa', 1, 'hendy-hertiasa-qnaufdqz', 129),
(1261, 'Alvanov Zpalanzani Mansoor', 1, 'alvanov-zpalanzani-mansoor-pwivvtkr', 129),
(1262, 'Lies Neni Budiarti', 1, 'lies-neni-budiarti-esujerfb', 129),
(1263, 'Agung Eko Budiwaspada', 1, 'agung-eko-budiwaspada-sesxggat', 129),
(1264, 'Achmad Syarief', 1, 'achmad-syarief-swiehesy', 129),
(1265, 'Adhi Nugraha', 1, 'adhi-nugraha-onfmiuyh', 130),
(1266, 'Harmein Khagi', 1, 'harmein-khagi-ituhnols', 130),
(1267, 'Agus Karya Suhada', 1, 'agus-karya-suhada-obzmovct', 130),
(1268, 'Dwinita Larasati', 1, 'dwinita-larasati-ziabkdva', 130),
(1269, 'Deddy Wahjudi', 1, 'deddy-wahjudi-czzckgzu', 130),
(1270, 'Meirina Triharini', 1, 'meirina-triharini-spwtsxfr', 130),
(1271, 'Asep Wawan Jatnika', 1, 'asep-wawan-jatnika-hrofogmm', 131),
(1272, 'Tri Sulistyaningtyas', 1, 'tri-sulistyaningtyas-voysbkdr', 131),
(1273, 'Yani Suryani', 1, 'yani-suryani-gfagarcq', 131),
(1274, 'Linda Handayani Sukaemi', 1, 'linda-handayani-sukaemi-jpgfyspl', 131),
(1275, 'Winni Aryuni', 1, 'winni-aryuni-jhjcxwqm', 131),
(1276, 'Puspita Nuari', 1, 'puspita-nuari-qkgeqgnn', 131),
(1277, 'Anuncius Gumawang Jati', 1, 'anuncius-gumawang-jati-ssgrtyto', 131),
(1278, 'Bambang Supriyanto', 1, 'bambang-supriyanto-kxaxkjjg', 131),
(1279, 'Nia Kurniasih', 1, 'nia-kurniasih-cetqfojw', 131),
(1280, 'Sutiadi Rahmansyah', 1, 'sutiadi-rahmansyah-vauhmoar', 131),
(1281, 'Lusia Marliana Nurani', 1, 'lusia-marliana-nurani-ttcsrucc', 131),
(1282, 'Dana Waskita', 1, 'dana-waskita-butuuhjd', 131),
(1283, 'Ayi Rohayati', 1, 'ayi-rohayati-xropenef', 131),
(1284, 'Untari Gunta Pertiwi', 1, 'untari-gunta-pertiwi-vpcxfqix', 131),
(1285, 'Shohib Khoiri', 1, 'shohib-khoiri-uhsbeyee', 131),
(1286, 'Elsa Silvia Nur Aulia', 1, 'elsa-silvia-nur-aulia-zwddyzpa', 131),
(1287, 'Sansan Ziaul Haq', 1, 'sansan-ziaul-haq-yjbatenj', 131),
(1288, 'Cecep', 1, 'cecep-rhsgrsqw', 131),
(1289, 'Asep Zaenal Ausop', 1, 'asep-zaenal-ausop-fczcadfp', 131),
(1290, 'Agus Syihabudin', 1, 'agus-syihabudin-ahmjjeeq', 131),
(1291, 'Muhamad Taufik', 1, 'muhamad-taufik-efbgcokq', 131),
(1292, 'Yedi Purwanto', 1, 'yedi-purwanto-uzykigxe', 131),
(1293, 'Qoriah', 1, 'qoriah-uricsttd', 131),
(1294, 'Onesius Otenieli Daeli', 1, 'onesius-otenieli-daeli-oxsywiap', 131),
(1295, 'I Nengah Kondra', 1, 'i-nengah-kondra-yxiyjfwl', 131),
(1296, 'Epin Saepudin', 1, 'epin-saepudin-nxeaqaro', 131),
(1297, 'Harry Nuriman', 1, 'harry-nuriman-ovfuumbd', 131),
(1298, 'Ade Engkus Kusnadi', 1, 'ade-engkus-kusnadi-wdmcybbz', 131),
(1299, 'Siti Kusumawati Azhari', 1, 'siti-kusumawati-azhari-zrvxtjvt', 131),
(1300, 'Pathmi Noerhatini', 1, 'pathmi-noerhatini-qyfhceus', 131),
(1301, 'Ernawati', 1, 'ernawati-vsoptmgo', 131),
(1302, 'Prima Roza', 1, 'prima-roza-thdzwogq', 131),
(1303, 'Dicky Rezady Munaf', 1, 'dicky-rezady-munaf-vbqidgnw', 131),
(1304, 'Acep Iwan Saidi', 1, 'acep-iwan-saidi-vwhaxghe', 131),
(1305, 'Rahayu Candradewi', 1, 'rahayu-candradewi-ozmqtohu', 131),
(1306, 'Amaliatun Saleha', 1, 'amaliatun-saleha-sndvucyw', 131),
(1307, 'Sonny Rustiadi', 1, 'sonny-rustiadi-aisljeul', 131),
(1308, 'Raden Roro Sri Wachyuni', 1, 'raden-roro-sri-wachyuni-tjpqhtum', 131),
(1309, 'Yasraf Amir P.', 1, 'yasraf-amir-p-fmujaxng', 133),
(1310, 'Oktofa Yudha Sudrajad', 1, 'oktofa-yudha-sudrajad-mqylfweu', 135),
(1311, 'Satya Aditya Wibowo', 1, 'satya-aditya-wibowo-igbverjj', 135),
(1312, 'Adita Pritasari', 1, 'adita-pritasari-yncjqykb', 135),
(1313, 'Salfitrie Roos Maryunani', 1, 'salfitrie-roos-maryunani-llstpqnv', 135),
(1314, 'Nila Armelia Windasari', 1, 'nila-armelia-windasari-gaqvppwj', 135),
(1315, 'Herry Hudrasyah', 1, 'herry-hudrasyah-ddeoiqow', 135),
(1316, 'Reinaldy Agung Pramudhita', 1, 'reinaldy-agung-pramudhita-yglklgve', 135),
(1317, 'Neneng Nurlaela Arief', 1, 'neneng-nurlaela-arief-gbvrmmnb', 135),
(1318, 'Aria Bayu Pangestu', 1, 'aria-bayu-pangestu-vutvyaxl', 135),
(1319, 'Umi Zuraida', 1, 'umi-zuraida-gcczniuh', 135),
(1320, 'Donald Crestofel Lantu', 1, 'donald-crestofel-lantu-uylspgqc', 135),
(1321, 'Dedy Sushandoyo', 1, 'dedy-sushandoyo-hmzolimc', 135),
(1322, 'Henndy Ginting', 1, 'henndy-ginting-kpihzhay', 135),
(1323, 'Hary Febriansyah', 1, 'hary-febriansyah-mlpucyhd', 135),
(1324, 'Prameshwara Anggahegari', 1, 'prameshwara-anggahegari-wajpnazm', 135),
(1325, 'Andika Putra Pratama', 1, 'andika-putra-pratama-afvpvebm', 135),
(1326, 'Achmad Ghazali', 1, 'achmad-ghazali-sxnhgqse', 135),
(1327, 'Khrisna Ariyanto', 1, 'khrisna-ariyanto-iuhzguhx', 135),
(1328, 'Shimaditya Nuraeni', 1, 'shimaditya-nuraeni-bcckucne', 135),
(1329, 'Ezra Hizkia Nathanael', 1, 'ezra-hizkia-nathanael-fftbdjyu', 135),
(1330, 'Utomo Sarjono Putro', 1, 'utomo-sarjono-putro-dwausaix', 135),
(1331, 'Valid Hasyimi', 1, 'valid-hasyimi-mtpvhsmj', 135),
(1332, 'Santi Novani', 1, 'santi-novani-cusyzwek', 135),
(1333, 'Nurtami Prihadi', 1, 'nurtami-prihadi-sjwqjdoe', 135),
(1334, 'Annisaa Novieningtyas', 1, 'annisaa-novieningtyas-pczdwhfa', 135),
(1335, 'Adhya Rare Tiara', 1, 'adhya-rare-tiara-lqiwftdd', 135),
(1336, 'Mandra Lazuardi Kitri', 1, 'mandra-lazuardi-kitri-vpububqm', 135),
(1337, 'Kurnia Fajar Afgani', 1, 'kurnia-fajar-afgani-mvjrdcam', 135),
(1338, 'Achmad Herlanto Anggono', 1, 'achmad-herlanto-anggono-dmbgdzcm', 135),
(1339, 'Isti Raafaldini Mirzanti', 1, 'isti-raafaldini-mirzanti-vnxbkhmx', 135),
(1340, 'Dina Dellyana', 1, 'dina-dellyana-cwlnzfus', 135),
(1341, 'Amilia Wulansari', 1, 'amilia-wulansari-blwgzkyh', 135),
(1342, 'Evy Rachmawati Chaldun', 1, 'evy-rachmawati-chaldun-rggrupug', 135),
(1343, 'Sri Herliana', 1, 'sri-herliana-aljeafub', 135),
(1344, 'Nurrani Kusumawati', 1, 'nurrani-kusumawati-jxtqgaoq', 135),
(1345, 'Ira Fachira', 1, 'ira-fachira-tcqsmekl', 135),
(1346, 'Fitri Aprilianty', 1, 'fitri-aprilianty-dgztkbnl', 135),
(1347, 'W. Victo Anggara Wisesa', 1, 'w-victo-anggara-wisesa-olzdmwfq', 135),
(1348, 'Veronica Afridita Khristiningrum', 1, 'veronica-afridita-khristiningrum-owleeidw', 135),
(1349, 'Emilia Fitriana Dewi', 1, 'emilia-fitriana-dewi-bnzlmrph', 135),
(1350, 'Inugrah Ratia Pratiwi', 1, 'inugrah-ratia-pratiwi-dytvrjtf', 135),
(1351, 'Eneng Nur Hasanah', 1, 'eneng-nur-hasanah-owmkvkie', 135),
(1352, 'Taufik Faturohman', 1, 'taufik-faturohman-uflbdbyj', 135),
(1353, 'Ana Noveria', 1, 'ana-noveria-omjarzya', 135),
(1354, 'Subiakto', 1, 'subiakto-ozpjmbxj', 135),
(1355, 'Meinanda Kurniawan', 1, 'meinanda-kurniawan-dfbtrkan', 135),
(1356, 'Dzikri Firmansyah Hakam', 1, 'dzikri-firmansyah-hakam-ezhqaxnq', 135),
(1357, 'Raden Aswin Rahadi', 1, 'raden-aswin-rahadi-lgcubcfn', 135),
(1358, 'Mustika Sufiati', 1, 'mustika-sufiati-gqdwtddz', 135),
(1359, 'Nurfaisa Hidayanti', 1, 'nurfaisa-hidayanti-caujynsl', 135),
(1360, 'Cahyaningtyas Nova Puspitadewi', 1, 'cahyaningtyas-nova-puspitadewi-wrifzlen', 135),
(1361, 'Sudrajati Ratnaningtyas', 1, 'sudrajati-ratnaningtyas-nrwkptab', 135),
(1362, 'Dermawan Wibisono', 1, 'dermawan-wibisono-fjwbwthv', 135),
(1363, 'Bambang Rudito', 1, 'bambang-rudito-sdtoakjl', 135),
(1364, 'Meditya Wasesa', 1, 'meditya-wasesa-xvxxekei', 135),
(1365, 'Pri Hermawan', 1, 'pri-hermawan-zpgoyzta', 135),
(1366, 'Sri Hartati', 1, 'sri-hartati-baafgndh', 135),
(1367, 'Qorri Aina', 1, 'qorri-aina-lomswfbb', 135),
(1368, 'Rendra Chaerudin', 1, 'rendra-chaerudin-mqauatfu', 135),
(1369, 'Manahan Parlindungan Saragih Siallagan', 1, 'manahan-parlindungan-saragih-siallagan-vzjyhqag', 135),
(1370, 'Deddy Priatmodjo Koesrindartoto', 1, 'deddy-priatmodjo-koesrindartoto-kwqufxgl', 135),
(1371, 'Acip Sutardi', 1, 'acip-sutardi-ckaapxpy', 135),
(1372, 'Sylviana Maya Damayanti', 1, 'sylviana-maya-damayanti-hnegqxhk', 135),
(1373, 'Nita Garnida', 1, 'nita-garnida-ceogvrzx', 135),
(1374, 'Jann Hidajat Tjakraatmadja', 1, 'jann-hidajat-tjakraatmadja-ssohqjht', 135),
(1375, 'Rafi Ndari Ardianto', 1, 'rafi-ndari-ardianto-ptpgvbjn', 135),
(1376, 'Mochammad Agus Afrianto', 1, 'mochammad-agus-afrianto-tkojdyht', 135),
(1377, 'Ilham Fauzan Putra', 1, 'ilham-fauzan-putra-selegwes', 135),
(1378, 'Anindia Pratiwi Putri', 1, 'anindia-pratiwi-putri-azyujbph', 135),
(1379, 'Dita Novizayanti', 1, 'dita-novizayanti-kazvgxtc', 135),
(1380, 'Lisandy Arinta Suryana', 1, 'lisandy-arinta-suryana-zbkzpavn', 135),
(1381, 'Atika Irawan', 1, 'atika-irawan-gppmodce', 135),
(1382, 'Madju Yuni Ros Bangun', 1, 'madju-yuni-ros-bangun-gknlkysf', 135),
(1383, 'Abel Tedjamulja', 1, 'abel-tedjamulja-ikgayzsq', 135),
(1384, 'Mohamad Yudiaputra Mashudi', 1, 'mohamad-yudiaputra-mashudi-bhmnaajy', 135),
(1385, 'Wipti Eka Prahadipta', 1, 'wipti-eka-prahadipta-dqdepjol', 135),
(1386, 'Mohammad Tedi Risnandar', 1, 'mohammad-tedi-risnandar-fqpwcjny', 135),
(1387, 'Daniel Karim', 1, 'daniel-karim-xqoqycul', 135),
(1388, 'Annisa Rizkia Syaputri', 1, 'annisa-rizkia-syaputri-dsizddsn', 135),
(1389, 'Togar Mangihut Simatupang', 1, 'togar-mangihut-simatupang-ieqsstsl', 135),
(1390, 'Brilliant Asmit', 1, 'brilliant-asmit-brfzmyaa', 135),
(1391, 'Vanessa Fitri Sabur', 1, 'vanessa-fitri-sabur-dwvrzwrp', 135),
(1392, 'Aurik Gustomo', 1, 'aurik-gustomo-yjgnlcun', 135),
(1393, 'Aminah', 1, 'aminah-ecfhnszl', 135),
(1394, 'Yudo Anggoro', 1, 'yudo-anggoro-ofuoaced', 135),
(1395, 'Wawan Dhewanto', 1, 'wawan-dhewanto-ymahyvfy', 136),
(1396, 'Muhammad Fakhrul Rozi Ashadi', 1, 'muhammad-fakhrul-rozi-ashadi-juordgsx', 136),
(1397, 'Ilma Nurul Rachmania', 1, 'ilma-nurul-rachmania-sjekdgui', 136),
(1398, 'Siti Mardiana', 1, 'siti-mardiana-iuflshmf', 136),
(1399, 'Asep Darmansyah', 1, 'asep-darmansyah-awupprnr', 137),
(1400, 'Sani Susanto', 1, 'sani-susanto-qwivspvb', 137),
(1401, 'Atik Aprianingsih', 1, 'atik-aprianingsih-bfeumzla', 137),
(1402, 'Harimukti Wandebori', 1, 'harimukti-wandebori-fdajagqx', 137),
(1403, 'Yos Sunitiyoso', 1, 'yos-sunitiyoso-bdwkvxut', 137),
(1404, 'G.N. Sandhy Widyasthana', 1, 'gn-sandhy-widyasthana-wycxkoav', 138),
(1405, 'Pennoh Philips Kembaren', 1, 'pennoh-philips-kembaren-ptwewxmo', 138),
(1406, 'Muhammad Hanafi', 1, 'muhammad-hanafi-zkewiuhz', 138),
(1407, 'Erman Sumirat', 1, 'erman-sumirat-vvoeeqnb', 138),
(1408, 'Yunieta Anny Nainggolan', 1, 'yunieta-anny-nainggolan-spodjmfl', 138),
(1409, 'Uke Marius Siahaan', 1, 'uke-marius-siahaan-quxpeckp', 138),
(1410, 'Sudarso Kaderi Wiryono', 1, 'sudarso-kaderi-wiryono-ykcphrdm', 138),
(1411, 'Reza Ashari Nasution', 1, 'reza-ashari-nasution-yobonavx', 138),
(1412, 'Sunu Widianto', 1, 'sunu-widianto-xbtpqrau', 138),
(1413, 'Isrochmani Murtaqi', 1, 'isrochmani-murtaqi-viepdoja', 138),
(1414, 'Anita Afriana', 1, 'anita-afriana-wkduyket', 138),
(1415, 'Detania Sukarja', 1, 'detania-sukarja-yeqtpzpn', 138),
(1416, 'Widhyawan Prawiraatmadja', 1, 'widhyawan-prawiraatmadja-cmzldtqf', 138),
(1417, 'Sahat Hutajulu', 1, 'sahat-hutajulu-kossydbh', 138),
(1418, 'Agung Wicaksono', 1, 'agung-wicaksono-ygaiskat', 139),
(1419, 'Jacob Silas Mussry', 1, 'jacob-silas-mussry-tnhabbih', 139),
(1420, 'Jemy Vestius Confido', 1, 'jemy-vestius-confido-qvugmgdt', 139),
(1421, 'Aries F Firman', 1, 'aries-f-firman-dsgonosx', 139),
(1422, 'Wiwiek M Daryanto', 1, 'wiwiek-m-daryanto-ynsalaas', 139),
(1423, 'Kinsenary Tjendrasa', 1, 'kinsenary-tjendrasa-fnlugnhp', 139),
(1424, 'Socrates Rudy Sirait', 1, 'socrates-rudy-sirait-rakvecoa', 139),
(1425, 'Anangga Wardhana Roosdiono', 1, 'anangga-wardhana-roosdiono-epdotbhd', 139),
(1426, 'Indra Cahya Uno', 1, 'indra-cahya-uno-ocxlkbpe', 139),
(1427, 'Hasto Kristiyono', 1, 'hasto-kristiyono-pzozmnqb', 139),
(1428, 'Mohammad Hamsal', 1, 'mohammad-hamsal-cvbauohf', 139),
(1429, 'Mohamad Toha', 1, 'mohamad-toha-ntqxxwzx', 139),
(1430, 'Iriawan Alex Ibarat', 1, 'iriawan-alex-ibarat-keniptug', 139),
(1431, 'Priyantono Rudito', 1, 'priyantono-rudito-prwitimx', 139),
(1432, 'Irwan Tri Nugroho', 1, 'irwan-tri-nugroho-grsgqekd', 139),
(1433, 'Mulya Amri', 1, 'mulya-amri-teervcha', 139),
(1434, 'Anh Dung Do', 1, 'anh-dung-do-yjzyshsy', 139),
(1435, 'Rusdian Lubis', 1, 'rusdian-lubis-ohvykdih', 139),
(1436, 'Taufiq Wisnu Priambodo', 1, 'taufiq-wisnu-priambodo-eliocvcs', 139),
(1437, 'Ruby Hermanto', 1, 'ruby-hermanto-wakokfwu', 139),
(1438, 'Agus Pratama Sari', 1, 'agus-pratama-sari-rywjdzsy', 139);