insert into public.faculties (id, institution_id, "name", code) values (1, 1, 'Fakultas Matematika dan Ilmu Pengetahuan Alam', 160),
(2, 1, 'Sekolah Ilmu Teknologi Hayati - Sains', 161),
(3, 1, 'Sekolah Ilmu Teknologi Hayati - Rekayasa', 198),
(4, 1, 'Sekolah Farmasi', 162),
(5, 1, 'Fakultas Teknik Pertambangan dan Perminyakan', 164),
(6, 1, 'Fakultas Ilmu dan Teknologi Kebumian', 163),
(7, 1, 'Fakultas Teknik Industri', 167),
(8, 1, 'Sekolah Teknik Elektro dan Informatika', 165),
(9, 1, 'Fakultas Teknik Mesin dan Dirgantara', 169),
(10, 1, 'Fakultas Teknik Sipil dan Lingkungan', 166),
(11, 1, 'Sekolah Arsitektur, Perencanaan dan Pengembangan Kebijakan', 199),
(12, 1, 'Fakultas Seni Rupa dan Desain', 168),
(13, 1, 'Sekolah Bisnis dan Manajemen', 197);